### ISSUE TITLE
Windows 下修改 hosts，应该能正常读取，并且提示升级权限？

### ISSUE THREAD

**Issue by Dreamer-Paul** [cxasm/notepad--#1]
![image](https://user-images.githubusercontent.com/25198337/180676721-ced84d6d-e7f4-46f3-a050-10ad28d9413a.png)

RT，我从知乎上看到大佬项目的，我记得 NPP 是可以升级权限并且可以保存编辑的，不如大佬考虑支持一下？

![image](https://user-images.githubusercontent.com/25198337/180677232-6b3b8f4a-587d-4ff5-8270-58a8ffce2123.png)

**Comment by cxasm** [comment]
已经修改了。
