### ISSUE TITLE
选择yaml格式后样式奇怪

### ISSUE THREAD

**Issue by sunzqe** [cxasm/notepad--#10]
在语言选项中如果选择yaml格式，样式很奇怪，如下图，key值很大，value值很小
![1663550509198](https://user-images.githubusercontent.com/20399909/190936849-9f8b5313-6784-499e-9029-d255de188c19.jpg)
在vscode打开就比较正常
![1663550593423](https://user-images.githubusercontent.com/20399909/190936918-32595618-3aae-41a0-b375-9a194ea2ee4d.jpg)

**Comment by cxasm** [comment]
编程语言字体风格，每种编辑器是自己定义的。
Notepad--目前对编程语言的风格设置，还不够友好。这部分高级功能，还需要完善。
需要对每种语言，每种属性字段，都要做可配置字体、颜色设置。后续我们会完善，尽量给出好的默认风格。

**Comment by cxasm** [comment]
最新版已经解决了。https://github.com/cxasm/notepad--/releases/tag/notepad-v1.16
用户可以对每种编程语言，每种属性，自己定义字体和颜色。
