### ISSUE TITLE
无法在32位系统上运行

### ISSUE THREAD

**Issue by liuxing01** [cxasm/notepad--#100]
可以在32系统安装，但无法在32位系统运行

![74bda39ccd3b3cb9](https://user-images.githubusercontent.com/35096100/217885710-b319b6ee-82e8-449b-b267-3d289f268c61.jpg)

**Comment by liuxing01** [comment]
![74bda39ccd3b3cb9](https://user-images.githubusercontent.com/35096100/217885511-61fca8ac-fea3-48f5-92f1-ad483cb39629.jpg)

**Comment by cxasm** [comment]
目前只发布了64位版本。

**Comment by cxasm** [comment]
不准备发布32位的程序了。
