### ISSUE TITLE
严重bug！保存后删除所有内容!!!!我积攒的论文句子全没了。。。。

### ISSUE THREAD

**Issue by ZCyueternal** [cxasm/notepad--#102]
![image](https://user-images.githubusercontent.com/46353699/217856960-e53202aa-4759-4218-8adc-6b6cec444a94.png)

**Comment by cxasm** [comment]
麻烦帮忙提交复现规律？感谢反馈。
另外，如果是崩溃，会有一个swap文件，在当前目录，看看是否存在，是隐藏的。
