### ISSUE TITLE
王局志安 最近的採訪 了解一下

### ISSUE THREAD

**Issue by sieginglion** [cxasm/notepad--#103]
https://youtu.be/yMcgd--dvr8

**Comment by Jacky89** [comment]
信王局 得永生 加油 特朗普保佑你

**Comment by cxasm** [comment]
如果你不是来提交bug，或者反馈需求，麻烦您不要再发帖了，可以吗？
开源是一件很严肃的事情。不要做一个讨人嫌的废物，做点事情，让这个世界变得美好？可以吗？

**Comment by sieginglion** [comment]
> 如果你不是来提交bug，或者反馈需求，麻烦您不要再发帖了，可以吗？ 开源是一件很严肃的事情。不要做一个讨人嫌的废物，做点事情，让这个世界变得美好？可以吗？

你先開的頭啊

**Comment by sieginglion** [comment]
我不會再發了，但你要知道你在公共空間闡述爭議性言論，勢必會有人回應

**Comment by cxasm** [comment]
你要发布言论，是你的自由。请在你自己的主页上表达，不要来这里。
这里都是和你思想不一样的人。

**Comment by kuohuanhuan** [comment]
> 这里都是和你思想不一样的人。

GitHub 也都是和你們思想不一樣的人。

**Comment by cxasm** [comment]
> > 这里都是和你思想不一样的人。
> 
> GitHub 也都是和你們思想不一樣的人。

我猜测你是日本鬼子的后代，不屑和你说。

**Comment by littzhch** [comment]
@sieginglion @kuohuanhuan 
你俩真的是够了，没事找个班上吧，issue 都关了还在这吵。我开通知不是为了观赏你俩的表演的。

**Comment by sieginglion** [comment]
是說 open source 行為是不是才是真正的共產呢？真正的超越國界的共產？

**Comment by sieginglion** [comment]
世界上唯一成功的真共產主義？
