### ISSUE TITLE
json格式化丢失精度

### ISSUE THREAD

**Issue by bigermini** [cxasm/notepad--#111]
Ndd Version v1.21.1

示例如图：

![图片](https://user-images.githubusercontent.com/117837101/218907691-2539c6cd-412d-4264-8bf9-4619541915cb.png)
![图片](https://user-images.githubusercontent.com/117837101/218907715-eee227d4-a9d8-45e1-8000-0547ea399286.png)

**Comment by cxasm** [comment]
1.23 版，将推出带json格式化的插件。

**Comment by cxasm** [comment]
请使用插件版的ndd2.1，提供了json插件支持json格式化。
