### ISSUE TITLE
打开时恢复上次未关闭的文件并未恢复对应的标签

### ISSUE THREAD

**Issue by zangxx66** [cxasm/notepad--#112]
步骤：
1.打开若干个标签
2.选择其中一个标签页面
3.关闭软件
4.重新打开软件
5.上次未关闭的文件正常恢复了，但没有激活关闭前的对应标签页面，默认激活了最后一个标签页面  
  
软件版本：1.22.2  
系统：windows 11

**Comment by cxasm** [comment]
已知问题。下个版本1.23解决。




409652570
***@***.***



&nbsp;

**Comment by cxasm** [comment]
1.23.2 已经完全解决该问题了。
