### ISSUE TITLE
希望添加注释功能

### ISSUE THREAD

**Issue by Lebhoryi** [cxasm/notepad--#117]
notepad++ 中有选项 设置行注释和取消行注释，希望添加这两个功能

**Comment by cxasm** [comment]
现在1.22.2版就是有的。不过没有快捷键，在右键菜单中。下个版本1.23增加快捷键。

**Comment by cxasm** [comment]
1.23.2已经完全解决。

**Comment by Lebhoryi** [comment]
牛逼啊，现在下载了全新版本 v2.0.0
正在试用
