### ISSUE TITLE
增加bookmark line功能

### ISSUE THREAD

**Issue by galwaychia** [cxasm/notepad--#12]
能不能像++那样，有搜索标记整行，复制标记行，清除标记，这样的功能呢？

**Comment by cxasm** [comment]
不太清楚您的版本，在最新版上面，标记功能、清除标记功能，是存在的。

**Comment by galwaychia** [comment]
可以试试notepad++。搜索a可以标记所有存在a的行，然后再去搜索b可以继续标记所有存在b的行，然后可以复制所有标记行，就可以复制出来所有存在a或者b的行，别粘贴到其它地方。

**Comment by cxasm** [comment]
懂了。其实就是查找关键字，在查找结果中，拷贝所有存在关键字的行内容。

**Comment by galwaychia** [comment]
> 懂了。其实就是查找关键字，在查找结果中，拷贝所有存在关键字的行内容。
对，还可以随时清除标记，追加标记，复制这些标记行，删除标记行。++做得挺完善的，可以试试看😂

**Comment by cxasm** [comment]
最新版解决了一部分，https://github.com/cxasm/notepad--/releases/tag/notepad-v1.16
完善了查找后结果，可以选中，复制行的功能。

**Comment by cxasm** [comment]
1.20已经彻底支持。
