### ISSUE TITLE
输入英文时，光标与实际存在偏离

### ISSUE THREAD

**Issue by zhen-NA** [cxasm/notepad--#120]
1.22.1版本，Archlinux + KDE环境 
输入英文字符的时候，光标偏移比实际的字符宽度小
中文字符无异常

**Comment by cxasm** [comment]
是屏幕进行了缩放导致。后续会改进。

**Comment by cxasm** [comment]
1个问题，1是屏幕缩放。2是主题下面的字体错误，请全局修改为等宽字体，不要用一些冷门字体。
