### ISSUE TITLE
全局设置中文fallback字体的功能有吗？

### ISSUE THREAD

**Issue by kmcbest** [cxasm/notepad--#125]
我希望英文字体设置为等宽字体如Consolas，中文字体则fallback到微软雅黑，这一点在全局格式统一设置里面的做不到（字体只能选一种），但在txt格式字体设置中却又可以。
![image](https://user-images.githubusercontent.com/689023/220541666-edc0c950-c1d6-49f0-aea0-8c1d691f83d4.png)

于是其他程序语言中的中文会fallback到宋体，不是很好看。

![image](https://user-images.githubusercontent.com/689023/220541614-c97f8afc-6e43-44ef-9a48-cd7ac28c1133.png)

**Comment by cxasm** [comment]
没有语言提供的语法着色是不一样的。只有txt提供了中英文分辨的语法。其余语言没有该用法。




409652570
***@***.***



&nbsp;

**Comment by kmcbest** [comment]
因为这主要只是从字体中字符集多寡的角度看，并不是语法高亮的问题，所以是不是应该从主程序来给全局的选项？

WIN11自带的记事本，也只有一个字体选项，设置一个英文等宽，中文还是会用微软雅黑，故有此一问。

**Comment by cxasm** [comment]
只有txt的语法提供了中英文不同字体，而且要注意不要使用小众字体，因为小众字体的宽度往往长短不一，很容易造成文字重叠。
除了txt以外，其余的编程语法，他的字体是编程语法高亮所决定的。
