### ISSUE TITLE
查找结果希望能follow np++

### ISSUE THREAD

**Issue by sfhgknsdfksdlf** [cxasm/notepad--#128]
首先作者的东西做的很好完成度已经比较高了
但还是有几个问题点，让我继续留在了++
我们会用np++来查找log，蛮清爽的

1. np++在当前文件中查找后，结果页的行间隔很小，字体页很小，整体看起来很紧凑，能显示更多信息；而np--的结果页行间距太大了，字体页太大了；并且np--无法通过按住CTRL+滚动鼠标滚轮  来缩放；就希望能follow np++，包括文本的间隔

2. 我自己的电脑由于安装了运行库，安装np--后可以直接打开使用；但是公司电脑没有安装运行库，安装np--后就打不开，希望安装包能做的兼容性更好一点。如果一个普通用户安装某个软件后打不开，可能就直接弃用了

3.好像tail -f功能，不知道是不是我没找到，tail -f对于开发调试是一个很实用的功能

做的好的地方：
工具栏的大图标和大间隔，看起来更舒适
文件对比功能

**Comment by cxasm** [comment]
正在完善查找结果框。
ndd将进入2.0系统。1.23是最后一个1.x系列，1.0系列是做基本功能。
2.0系列就开始完善细节，性能提升，发动社区提交插件。

**Comment by cxasm** [comment]
1.23.2 tailf 是存在的。但是还需要完善性能，如果文件太大，频繁修改可能taif存在性能问题。
2.0发布时，会完善tailf性能。这里的性能我们肯定会超越同类产品的。

**Comment by sfhgknsdfksdlf** [comment]
> 
goodjob 

1、不过感觉行间距还是有点大，主要是行号太大了 
     可以看到np++行号和文本的字号是一样大的，同一份文件np++只要更少的height就能显示同样的内容； 
     np--的行号比文本字号大，导致文本的行间距就大了好多  

2、查找结果，np++是关键字黄色背景红色字体，查看起来更显眼  

3、np++有缩放快捷键，CRTL + /可以快速恢复默认的缩放比例
4、np--的查找结果页的字体貌似有点太小了，途图中的查找结果我是做了放大的，由于没有恢复默认缩放的功能，我也不知道np--默认缩放是多大
5、np--用正则表达式查找后，关闭np--再重新打开，查找模式就重置为普通了，np++是能记住的

6、同一行多次匹配，最新版np++已经只在查找结果中显示为一行了，np--在同一行中匹配到了n次，就会将该行重复显示n次

最后希望能兼容toml配置文件吧，这个新的配置文件格式蛮好用的

不得不说np++的布局还是有他的科学性的，所以才会有这么多用户选择np++，相信作者也是同样的原因使用的np++
所以还是建议能先follow np++，这样用户在拿np--做替代品的时候才能更加平滑



![Snipaste_2023-03-12_02-21-08](https://user-images.githubusercontent.com/113858507/224505182-a092167a-bf8e-4462-a5fb-425fb66fb08b.png)

**Comment by sfhgknsdfksdlf** [comment]
np--不仅能在查找结果中高亮，还能再原文中把关键字高亮，我个人觉得是蛮不错的
因为我经常会从查找结果跳转到原文看更详细的内容，np++在原文中是不会高亮关键字的，看着有点不太直观
