### ISSUE TITLE
希望文件比较时，缩略图可以点击，快速定位

### ISSUE THREAD

**Issue by icewindq** [cxasm/notepad--#130]
希望文件比较时，可以点击右侧的缩略图，快速滚动到对应位置
![image](https://user-images.githubusercontent.com/6817601/221538201-24bec25d-2deb-4f54-aa6d-26a587db4186.png)

**Comment by cxasm** [comment]
可以。下来会完善细节。

**Comment by cxasm** [comment]
2.1 已经发布，已经支持。
