### ISSUE TITLE
希望把.cmd扩展名识别成batch script

### ISSUE THREAD

**Issue by Coresi7** [cxasm/notepad--#133]
希望把.cmd扩展名识别成batch script

另外，对于混合分辨率支持不全：比如说弄个4K屏幕，放大150%，且这台电脑同时接了一台放大100%的1080p，则notepad--的字体会显得非常大

**Comment by cxasm** [comment]
第一个问题，自定义即可。
![image](https://user-images.githubusercontent.com/42246867/221865438-a6ca5c72-450f-446d-8bb8-7e9edb694227.png)

第二个问题，两个屏幕，分辨率不一样，是有该问题，待改进。
