### ISSUE TITLE
可否增加ANSI编码

### ISSUE THREAD

**Issue by ostoe** [cxasm/notepad--#140]
之前经常copy文档到notepad++里面查看是否有零宽度字符或者特殊字符，utf-8看不出来的，用ansi可轻松看出来

**Comment by cxasm** [comment]
请及时更新到 ndd 2.0 版本。就在github 主页。

**Comment by ostoe** [comment]
感谢回复，更新后有特殊字符的情况下，切换到ansi/gbk编码默认会采用gbk，没办法单独切到ansi编码，依旧无法看出文本中隐藏了特殊字符

**Comment by cxasm** [comment]
暂时不做技术性解释。 ansi 在中国就是gbk编码。如果看不出特殊字符，则说明文本不是gbk编码。ndd使用的是gb180系列编码，可以支持7万多个汉字。
