### ISSUE TITLE
Opening files on mounted drives

### ISSUE THREAD

**Issue by egbertn** [cxasm/notepad--#142]
Just as with Notepad++ Notepad-- cannot deal with mounted drives, e.g. files on a USB stick. 
Is this going to be addressed?
Thanks.
Further, like this tool, esp on non-windows machines

**Comment by cxasm** [comment]
I will come down and have a look.

Now it can support the maos linux system, and you can compile linux yourself. We only maintain domestic Uos. Other Linux systems are maintained by the community.

**Comment by cxasm** [comment]
The latest code is here ：https://gitee.com/cxasm/notepad--
we in china, open github web and commit source code very slow。

**Comment by egbertn** [comment]
Thanks We can close the issue. Though from snap, it is not able to 'see' files on mounted drives, compiling myself to see if it solves the issue, is one bridge too far for this.
