### ISSUE TITLE
在搜索结果列表中,复制快捷键不能复制选中文本

### ISSUE THREAD

**Issue by MaryDBurke01** [cxasm/notepad--#150]
首先使用在文件夹中搜索功能进行搜索,然后在搜索结果列表中,使用快捷键进行复制,没有复制成功

**Comment by cxasm** [comment]
请更新版本到2.0以上。

**Comment by MaryDBurke01** [comment]
使用2.1.0好像还是一样的问题,在搜索结果列表中还是没法使用快捷键进行复制

**Comment by cxasm** [comment]
感谢反馈。是有该问题。下个版本2.2解决。

**Comment by MaryDBurke01** [comment]
感谢制作这么优秀的工具,用着很顺手

**Comment by cxasm** [comment]
应该是没有该问题了，最新版是2.5,2.4也是支持 该问题的。
