### ISSUE TITLE
文本编码批量转换可选部分文件转换

### ISSUE THREAD

**Issue by siweijianrong** [cxasm/notepad--#154]
您好，请问是否可以增加一个功能，文本编码转换只转换勾选的相关文件，因本人使用是需要把一个文件夹下的不同文件转换成不同编码，但其后缀名可能是一样的。
另外文本编码转换是否可以使用非模态窗口，不影响原有窗口的文本编辑。

**Comment by cxasm** [comment]
已知晓。不支持定做功能。
