### ISSUE TITLE
高分屏

### ISSUE THREAD

**Issue by ingxhe** [cxasm/notepad--#160]
![image](https://user-images.githubusercontent.com/30750321/231109000-2aa0b383-54ad-4bca-b92b-b299ff1fc0d7.png)
和屎一样，notepad++永远的神

**Comment by ingxhe** [comment]
![image](https://user-images.githubusercontent.com/30750321/231109848-9d65965b-d02e-46eb-b40a-7ec00d51b635.png)

**Comment by ingxhe** [comment]
![image](https://user-images.githubusercontent.com/30750321/231110994-b71a4ee9-30e8-4115-9d6b-ba69b314a8c3.png)

**Comment by ingxhe** [comment]
![image](https://user-images.githubusercontent.com/30750321/231111638-281aab17-ded4-4530-98dc-86fbc1598733.png)

**Comment by cxasm** [comment]
感谢反馈，用什么软件是您的自由。
