### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by UjuiUjuMandan** [cxasm/notepad--#168]
deleted

**Comment by cxasm** [comment]
感谢帮ndd做宣传，如果能够提交到人民日报，头版头条，就更好了 。

开始着急了，呵呵，竞争不过，开始走人生攻击的路线啦。

**Comment by UjuiUjuMandan** [comment]
Notepad-- 对诋毁者们恶意歪曲事实的说明
https://zhuanlan.zhihu.com/p/609383171

March 03, 2023

近期，一些有计划和预谋对ndd进行诋毁的发帖，在知乎等媒体上恶意哗众取宠。为避免不明真相的网友被npp反动势力蛊惑，Ndd项目特予以申明。以正本清源，治病救人。为何要治病救人？许多npp的反动势力和走狗，已经被敌对思想严重洗脑，如果再不治疗，怕是要做出更多出格、害人害己的事情。

最早，是一个github中化名疑是来自日本的小号，上来就喷Ndd抄袭，说Ndd不是开源项目，敢不敢开源，让全球程序员看看代码？这个叫嚣的走狗，连最基本的情况都没有摸清楚，可见就是为了喷而喷！当时ndd项目已经开源了，代码是1.19版本，已在github上面开源至少三个多月。而走狗上来就说Ndd代码不是开源的，可见其喷的多么仓促。事后，该走狗立刻修改github上面的issue提问，删除了“ndd敢不敢开源代码？”的可笑质疑。至于后面，看到ndd的确是开源，而且框架核心代码都是自研后，便开始胡搅蛮缠扯一些“gpl协议”，“应该有参考npp的代码”等诸多陷阱问答和鸡毛蒜皮的事情。

对此，Notepad double decrease（下简称ndd)已经多次声明，Ndd是开源项目，所有代码都是基于QT/CPP的自研实现，使用了开源项目qscint。Ndd的优势是，不仅可以在windows上运行，而且可以在mac/uos/深度/麒麟/ubutu/archlinux/等诸多操作系统和架构上运行。Ndd是作者在2019年编写cc compare对比软件的副产品，具体说明见文章：《我为什么要开发自己的软件——CC Compare作者的自述》[我为什么要开发自己的软件——CC Compare作者的自述](https://web.archive.org/web/20230423013208mp_/https://zhuanlan.zhihu.com/p/607057675)。还有文章《[编写一个ndd ，去替换npp ,我是认真的](https://web.archive.org/web/20230423013208mp_/https://link.zhihu.com/?target=https%3A//github.com/cxasm/notepad--/wiki/%25E7%25BC%2596%25E5%2586%2599%25E4%25B8%2580%25E4%25B8%25AAndd-%25EF%25BC%258C%25E5%258E%25BB%25E6%259B%25BF%25E6%258D%25A2npp--%2C%25E6%2588%2591%25E6%2598%25AF%25E8%25AE%25A4%25E7%259C%259F%25E7%259A%2584)》编写一个ndd ，去替换npp ,我是认真的

随后知乎多个账号，其中IP显示几个来自日本、香港、上海等地的账号，开始在知乎上面自问自答，恶意诋毁Ndd。无非还是那些旧问题，恶意诋毁Ndd项目是抄袭，蹭热点，政治舔狗，打着爱国来骗钱，强制收取赞助费乞讨等等。对此Ndd作者专门写了一篇文章《Notepad--让反对势力更加着急和头疼》，予以反击。见[Notepad--让反对势力更加着急和头疼](https://web.archive.org/web/20230423013208mp_/https://link.zhihu.com/?target=https%3A//github.com/cxasm/notepad--/wiki/Ndd-%25E8%25AE%25A9%25E5%258F%258D%25E5%25AF%25B9%25E5%258A%25BF%25E5%258A%259B%25E6%259B%25B4%25E5%258A%25A0%25E7%259D%2580%25E6%2580%25A5%25E5%2592%258C%25E5%25A4%25B4%25E7%2596%25BC)

事到如此，我作为一个土生土长的中国程序员，终于有所领悟：npp走狗势力在国内互联网已经十分猖狂，务必要加快进行国产软件的可替代。

在我没有开发ndd之前，我和国内老百姓一样，都在使用npp。我们觉得反正是免费软件，又不收钱，白用就用吧。现在想起来，我真是太单纯了！当我无意中因为不想被npp言论恶心，随手自研ndd，试图去全面替换npp的时候，npp走狗针对ndd有组织有预谋的诋毁运动开展了。我才发现这背后绝对不是“开源免费使用”那么简单！npp的作者绝对不是一个人，它的背后是一套有组织有预谋的敌对势力，他们的目标，绝不仅仅是喊喊口号，而是和境外分裂台湾、新疆等势力勾结在一起，收取境外敌对势力的赞助费，为境外敌对势力做“颜色革命”推波助澜。

以前我的出发点，仅仅是让国内用户能够有选择，可使用免费的跨平台编辑软件ndd。现在ndd遭到npp的恶意诋毁后，我更有必要给老百姓普及这一切——npp的背后，是一套收取境外敌对势力赞助费，试图分裂中国，发起“颜色革命”反对势力。不要给我扯什么高深的政治，这是文盲都能够理解的事情。不要说我反对“境外势力分裂中国”就是扯政治，我说这不是什么政治，这就是作为一个中国人，哪怕是文盲，也应该反对的东西。

关于蹭热点，我已经回应过多次了。我记得郭德纲说过，当他在北京连打车回通州的一块二毛钱都没有的时候，没有人说老郭咋样咋样。当网上有Notepad/Notepad2/Notepad3/Notepaeqq/Notepad Next等等的时候，没有人关心以上那些是不是抄袭。我在前期开发Notepad--的过程中，被同行不看好，说东西做的差，没前途，不会有市场。那时候没人说Ndd是蹭热度，因为当时Ndd寂寂无闻，无人关心。突然有一天，有人说Notepad++观点错误，找找替代品时，有人发现Notepad--还凑合能用。媒体一发布，Notepad--慢慢就火了。这时候已经过去了三年！要说蹭热度，那么之前三年无人问津的时候，没人说Ndd是蹭热度，反而还总被人说名称不行，注定没市场？

Npp的走狗们总是强调，ndd花了大量的钱，去收买国内的媒体，一天到晚铺天盖地的打广告。呵呵，真是怪了。npp走狗们在贬低ndd项目业余，做得充满“抖音味”的时候，无非是嘲笑ndd的投入不足，界面简单，许多功能都没有，连个像样的图标都画不起，还要去捡其它软件的图标。不对，npp走狗们画风一转，说ndd财大气粗，花了大价钱，请了大量的软文写手，收买国内的媒体，去打广告推广ndd。看吧，这就是npp走狗们的典型思维，反正要说你咋样，就咋样，完全不顾基本事实，哪怕是前后自相矛盾。

关于npp走狗污蔑ndd“政治舔狗，打着爱国来骗钱，强制收取赞助费乞讨”的诋毁。npp的教主和走狗们的逻辑就是，npp要分裂台湾，甚至新疆，他们的言论是“正确的政治”;而ndd作者作为一个基本的中国人，反对分裂中国的言论，npp就开始给ndd贴标签，说ndd是“政治舔狗”，这一招真是十分歹毒，用心险恶。

npp走狗在无形之中，利用一些中国底层老百姓，对社会或政府不满的潜意识心态，来攻击任何说“正确的话”的言论。这就好比，敌人故意把尿水泼在你身上，你用手去擦，敌人再嘲笑说你满手都是尿。如果npp专心做软件，不发布分裂中国的祸心言论，还会有它们口中的“政治舔狗”ndd吗？npp作者和走狗，为了推广软件，为了收割一点赞助费，沦落到了卖主求荣、出卖灵魂的地步，我不开玩笑的警告npp的作者，这是一条不归路。（我知道npp作者能够看到这篇文章，所以你不要笑）同时ndd申明，对npp这种无形转移矛盾，升级矛盾，大扣帽子的行为，强烈鄙视与反对。

前文已提过，ndd的作者作为一个中国人，不关心政治，也不对政治感兴趣，但是哪怕一个文盲，都知道“分裂中国”是极其歹毒、包藏祸心的险恶用心。ndd的作者只是说“严重反对npp利用开源软件去分裂中国”，就被npp走狗扣上“政治舔狗”的标签，ndd是无论如何也不能同意其观点的。如果说“反对任何分裂中国的言论”的说法是错误的，那么14亿中国人，可能有99.9999%都是错误的，剩下那一小撮，是日本鬼子遗留在中国的后代。所以广大的网友，不要被npp的错误言论转移矛盾。ndd不涉及政治，不关心政治，更不会做什么政治舔狗。只是作为一个中国人，不允许分裂祖国，这是基本原则。还有，如果一个人在中国过的不好，就希望中国分裂，这是极其极端的错误思想，这种思想和行为会害了周围的人，在任何国家，任何地区，这种人的思想都是错误和不受欢迎的。

ndd再次重申，ndd不涉及任何政治，任何官方的政治活动，ndd项目都不感兴趣，也不会去参与。但是如果npp作者和走狗，要试图再瞎BB伤害中国人民感情的言论，ndd是坚决要反对和反击的。即ndd不涉及任何政治，反对的是npp伤害中国人民感情的言论，对此ndd是要坚决替换npp的。

关于npp诋毁ndd是“打着爱国来骗钱，强制收取赞助费乞讨”，这才真是说对了一半，对的一半是“npp真是来乞讨赞助费的”；错的一半是，这个软件恰恰是npp，而不是ndd。为什么呢？npp靠发布分裂中国的言论，去乞讨收取境外敌对势力的赞助费，这是“冒天下之大不韪”，也是事实。反观ndd，从来没说过“爱国就用ndd”，从来都是让用户有另外一种选择的可能，更没有什么强制收取赞助费的行为。ndd从第一行代码敲下开始，或许是想做个商业软件，通过正常合法的商业软件去获取正当利润，从来也没想过通过“贩卖爱国”情怀去赚钱。

事实上，如果ndd不能提供给用户基本的编辑器功能，又何谈替换和赚钱呢？如果一个人天天喊着“爱国”，真有用户给他交费和赞助吗？还有“强制收取赞助费”更是可笑，所有的赞助都是自愿行为，有任何人，任何用户，说他被ndd强制收取过赞助费吗？可想而知，npp的走狗，在污蔑ndd的时候，简直是无所不用其极，他们真是害怕了，害怕ndd的替换行动，这是在ndd没有问世之前绝无仅有的表现，ndd表示很满意npp的高度害怕。

再说赞助费，这个已经说过多次了。现在写一篇文章都可以贴上一个赞赏费的入口，看一场直播都有那么多人赞赏。我写个软件，免费给老百姓使用，收取个赞赏费，怎么了，犯了多大的错误？犯得着那么喷吗？npp走狗们要是闲的发慌，无中生有、混淆视听，不如去帮助下老弱病残。还有劝告个别眼红的同行，有这闲工夫喷同行，为什么自己不也去做一款“国产可替代”的软件，来让老百姓免费使用呢？顺便挣点赞赏费，正大光明的挣钱，有什么好喷的？一切痛苦都是对自己无能的愤恨，与其眼红别人，不如努力提升自己。

ndd作者是一个普通老百姓，不管做什么，最终还是要生活，要盈利吧？毕竟谁都要养家糊口，都是普通老百姓。Ndd没有靠卖注册码盈利，但是那些喷子，连捐赠都喷！Ndd是有底线的，咱可不能学npp的作者去收境外反对势力的赞助费！喷子的逻辑就是，国家和个人不投一分钱，所有软件就能自然出来。诋毁Ndd靠捐赠就是乞讨，好像开源人士就是神仙，不吃不喝，不需要付出劳动，就能把软件做出来一样。我的理解是，捐赠是一种众筹行为，而且gitee官方也是支持捐赠的，所有捐赠众筹都是一种自愿行为。

所以还请npp的势力和喷子们，做个正常人吧! 立即停止再说一些“分裂中国、反智商、诋毁ndd”的错误言论。

**Comment by znlgis** [comment]
我咋还看懵了，这是啥操作

**Comment by cxasm** [comment]
> 我咋还看懵了，这是啥操作

反动派又开始搞下作，下流的事情了。见怪不怪，来个匿名搞人身的攻击的牛鬼蛇神，多半是日本鬼子的后代。

**Comment by clqs803** [comment]
垃圾人，以后生孩子不怕没PY吗？

**Comment by UjuiUjuMandan** [comment]
> 垃圾人，以后生孩子不怕没PY吗？

对不起，这是我们最后一代。

**Comment by Fxiao1** [comment]
> > 垃圾人，以后生孩子不怕不PY吗？
> 
> 这是我们最后一代，谢谢！

你们鬼子是不是不懂中文，哈哈，你看你回复的是个什么玩意儿？

**Comment by UjuiUjuMandan** [comment]
> > > 垃圾人，以后生孩子不怕不PY吗？
> > 
> > 
> > 这是我们最后一代，谢谢！
> 
> 你们鬼子是不是不懂中文，哈哈，你看你回复的是个什么玩意儿？

哈哈，你说话真有意思。

**Comment by UjuiUjuMandan** [comment]
哈哈，你的妈妈的。

**Comment by Fxiao1** [comment]
> 哈哈，你的妈妈的。

傻逼狗子真难受，不敢用自己的母语说话，只能咿呀学舌学别人的话，还学的如此拙劣，最可笑的是就不会几个汉字，还妄想用来骂人？是不是很难受？身为狗，不敢承认自己是狗，尽管大家都看的出来，你还在小丑般的装人，装不出来的，畜牲。

**Comment by UjuiUjuMandan** [comment]
> > 哈哈，你的妈妈的。
> 
> 傻逼狗子真难受，不敢用自己的母语说话，只能咿呀学舌学别人的话，还学的如此拙劣，最可笑的是就不会几个汉字，还妄想用来骂人？是不是很难受？身为狗，不敢承认自己是狗，尽管大家都看的出来，你还在小丑般的装人，装不出来的，畜牲。

是是是，宁说的对。
