### ISSUE TITLE
无法输入中文

### ISSUE THREAD

**Issue by Stcjh** [cxasm/notepad--#175]
如题，系统为centos stream9 ，使用版本为subtwo-v2.3-redhat7.4-x86_64.AppImage，无法正常输入中文

**Comment by cxasm** [comment]
默认支持ibus输入法。建议centos下面安装中文拼音输入法，然后使用ibus接口。
因为是linux系统，默认您懂这些操作。

**Comment by Stcjh** [comment]
ibus拼音输入法是有安装的，而且在gedit，firefox浏览器都是正常输入的。不过现在已经解决了。
