### ISSUE TITLE
超过100M分块加载有问题，且无法搜索未加载块中的内容

### ISSUE THREAD

**Issue by Glenn1Wang** [cxasm/notepad--#176]
rt

**Comment by cxasm** [comment]
2.3 加载是没有问题的。不知有何问题 ？注意是大文本，如果文件不是文本，则加载显示肯定是乱码不对的。
大文件搜索，2.4可以支持，马上会发布。

**Comment by Glenn1Wang** [comment]
正常滚轮滑动，只能显示第一块的内容，只有手动调节这个才能显示后续内容
![image](https://user-images.githubusercontent.com/22832225/236728753-147188ee-b974-4695-8ab0-5fd57994b7d0.png)

**Comment by cxasm** [comment]
> 

目前就是这样设计的，是自有的特性导致。ndd大文本可以打开8G一下文件。超大文本可以无限制打开任意大文件。
这样设计可以快速滑动定位到指定的块，占用内存极少，否则一次性加载，内存不够。
