### ISSUE TITLE
需求：ndd V2.4绿色免安装版，在格式化后请增加折叠功能

### ISSUE THREAD

**Issue by hehuaguo90** [cxasm/notepad--#181]
在JSON格式化后会有很多层级，请在V2.5+ 增加按{  } [   ]  增加折叠代码功能，参考Ultra Editor。

**Comment by cxasm** [comment]
2.4 是有相关快捷键功能的，请查看。
![image](https://github.com/cxasm/notepad--/assets/42246867/2ad2e9c9-ccb8-4e10-a8fe-49fab7408725)
