### ISSUE TITLE
error: ‘isClearSwpFile’ was not declared in this scope

### ISSUE THREAD

**Issue by steventracy** [cxasm/notepad--#184]
src/cceditor/ccnotepad.cpp:5503:32: error: ‘isClearSwpFile’ was not declared in this scope
 5503 |                 if (success && isClearSwpFile)

Ubuntu 22.04.2

**Comment by cxasm** [comment]
这是一个很简单的编译问题，请自行解决一下。

**Comment by Mr-Second** [comment]
https://github.com/cxasm/notepad--/issues/201#issuecomment-1633502461

**Comment by dijkstar0317** [comment]
![image](https://github.com/cxasm/notepad--/assets/143583985/c030a3f8-cee9-453b-a952-fdcf6fc8828c)
如图，删掉注释的即可
