### ISSUE TITLE
有无Mac安装包

### ISSUE THREAD

**Issue by 45gfg9** [cxasm/notepad--#2]
（是 Intel Mac

或者，会支持Apple ARM么

**Comment by cxasm** [comment]
现在还没有，后续会发布。在uos系统上有版本。

**Comment by Xinshao520** [comment]
谢谢作者的努力，期待Mac版发布！

**Comment by cxasm** [comment]
已经发布了一个版本，还请试用。

**Comment by Xinshao520** [comment]
非常感谢作者开发～发自我的手机-------- 原始邮件 --------发件人： "zuowei.yin" ***@***.***>日期： 2022年8月29日周一 10:24收件人： cxasm/notepad-- ***@***.***>抄送： 心旓 ***@***.***>, Comment ***@***.***>主    题： Re: [cxasm/notepad--] 有无Mac安装包 (Issue #2)

已经发布了一个版本，还请试用。

**Comment by haodong5502** [comment]
期待notepad-- for mac m1

**Comment by cxasm** [comment]
> 期待notepad-- for mac m1
已经发布了一个m1的版本。请看1.14 release 的 mac-m1_12.3.dmg
