### ISSUE TITLE
说了不谈政治自己在bb什么？去医院看看吧

### ISSUE THREAD

**Issue by fangchaooo** [cxasm/notepad--#204]

**Comment by cxasm** [comment]
人渣，你好。

**Comment by Darmau** [comment]
老中人的不谈政治：拥护共产党

**Comment by fangchaooo** [comment]
> 人渣，你好。

指出问题==人渣，你这说话当放屁的人==智障吧

**Comment by cxasm** [comment]
请后面的兄弟伙，直接恢复“人渣，你好”即可，不需要过多口水仗，一人一口唾沫星子，淹死这个“人渣”。

![image](https://github.com/cxasm/notepad--/assets/42246867/435fc7d1-0b4f-4757-84eb-26e30816cb02)

**Comment by fangchaooo** [comment]
^-^

**Comment by Kanofans** [comment]
怎么没在隔壁见你叫啊？人渣？

**Comment by Yelon-Xuanvin** [comment]
那你用隔壁那个去，你可以滚了

**Comment by clqs803** [comment]
> 那你用隔壁那个去，你可以滚了

这B可能就是隔壁派来的dog

**Comment by clqs803** [comment]
作者请继续并加大力度，反H狗们快破防了~

**Comment by Pinghigh** [comment]
> _No description provided._

不谈政治不等同于反对谈政治的人。

**Comment by huangkaiqiao** [comment]
人渣，你好。

**Comment by Hiyajomaho-num9** [comment]
本来想着打一大段字，但想想没必要对你这种人讲啥道理，毕竟你也不会听
so

**人渣，你好。**

**Comment by Unysno** [comment]
哈哈哈

**Comment by lucifer662607004** [comment]
英雄你好，加油，支持

**Comment by shtdbb** [comment]
您是语文不及格还是逻辑不过关？作为一个GitHub的用户，居然没有逻辑思维，这才让人遗憾。建议您仔细阅读后再看看您的这个提问，养成良好的思考和认知的素养。

**Comment by fangchaooo** [comment]
全是三无账号，笑死

**Comment by fangchaooo** [comment]
> 

你和弱智没区别

**Comment by fangchaooo** [comment]
> 本来想着打一大段字，但想想没必要对你这种人讲啥道理，毕竟你也不会听
> 
> so
> 
> **人渣，你好。**

我知道你这样的弱智是这样

**Comment by fangchaooo** [comment]
> > 那你用隔壁那个去，你可以滚了
> 
> 这B可能就是隔壁派来的dog

你含着习近平jb我都不会破防

**Comment by cxasm** [comment]
继续闹腾吧，现在是急了；往后就是怕了，最后就是悔了。
等台湾回归了，有你狗日地哭的时候。

**Comment by fangchaooo** [comment]
> 继续闹腾吧，现在是急了；往后就是怕了，最后就是悔了。 等台湾回归了，有你狗日地哭的时候。
哈哈，你五等贱民还想呀，港澳回来了也没见你能自有出入呀，人还不是你祖宗，多贱还要再给你自己找个台湾爹

**Comment by rnmeow** [comment]
友軍，你好！
