### ISSUE TITLE
不支持UTF-16文本文件

### ISSUE THREAD

**Issue by geeziy** [cxasm/notepad--#206]
打开UTF-16编码的文本文件，显示为乱码

**Comment by cxasm** [comment]
这种编码 utf-16-le 有时候会识别错误。
一般这种编码，头部要带一个 bom 才行。
可以 以 utf-16-le 编码打开即可。保存的时候，建议带上bom头，下次就不会出问题了。

请使用2.6版本。

**Comment by geeziy** [comment]
好的，可以了
