### ISSUE TITLE
功能建议：丰富“编辑”功能及插件支持

### ISSUE THREAD

**Issue by yttoeq** [cxasm/notepad--#21]
建议菜单的“编辑”功能中增加行操作等功能，另外如能直接兼容notepad++的插件那更好。^_^ 辛苦了！

**Comment by cxasm** [comment]
1.17中已经丰富不少。插件我们后面肯定会支持的，不过现在开发者参与的太少，插件还没有提上高优先级。

**Comment by cxasm** [comment]
1.17.2已经解决。
