### ISSUE TITLE
Vietnamese Text Editor

### ISSUE THREAD

**Issue by iahunq** [cxasm/notepad--#214]
I hope I don't become scum or a scumbag after I introduce this text editor. The UI is not as polished as NDD. This is understandable, as the developer has to design everything from scratch (and I think he is really not good at that). It's also a Windows-only application, so it can't compete with NDD in terms of cross-platformness.

Disclaimer: I'm not related to the Vietnamese developer. Github suggested it to me. Apart from a somewhat rough UI, it has many features that NDD doesn't have.

https://github.com/vinadevs/VinaText

**Comment by cxasm** [comment]
Not related to the NDD project.
