### ISSUE TITLE
"notepad-- 2.6 版本存在恶意行为" 告警询问

### ISSUE THREAD

**Issue by xWenChen** [cxasm/notepad--#229]
我在公司的电脑上下载了 notepad-- 2.6，某一天不知道使用了什么功能，安全人员给我发了个告警信息，提示我 notepad--v2.6.0-win10-portable\notepad--.exe (PID：8848)存在恶意行为，应用被安全侧关闭了，并给我发了消息。随后我就把notepad--删除了。

我重新下载了 sublime text，sublime text 使用起来没问题。

希望 notepad-- 的小伙伴能查下是什么引发了告警哇？是不是有木马或者敏感 api 的调用？

**Comment by sinomiko** [comment]
是因为Optional macro recording hook 录制宏，运行宏这个功能吧，把这段代码移除，重新编译下试试

**Comment by cxasm** [comment]
升级到2.7版本一下。目前没有发现问题。

**Comment by xWenChen** [comment]
ok，我后面试试
