### ISSUE TITLE
文件恢复可能会成为灾难

### ISSUE THREAD

**Issue by hy1080** [cxasm/notepad--#247]
可能是在关机时没有把程序关闭的原因（可能），每次开机后都会提示恢复文件。
此时如果选择恢复。很可能就把真正保存了的内容给搞没了。。。

**Comment by cxasm** [comment]
该功能并不是你所想的那样。不会自动恢复，只会打开恢复目录，让用户手动去找回需要恢复的文件。

**Comment by hy1080** [comment]
事实上我的文件已经丢失了。但是并没有打开恢复目录。。。。。。。。
