### ISSUE TITLE
试用后的一点建议

### ISSUE THREAD

**Issue by Jiangxp16** [cxasm/notepad--#248]
试用了一下，提点个人建议。
一直想找一个npp的替代工具，但找了一圈没有发现一个轻量级的文本编辑器能同时实现下面这两个功能的：
1. 分栏编辑
2. 函数列表视图（可按名称、位置等条件排序）
希望能加入这两个功能。
另外，npp打开大文件很慢一直是个问题，ndd如果能解决这个问题就更好了。ndd的界面比npp好看一些，但目前而言，响应更慢，打开几MB的文件，拖动窗口都有明显的卡顿，希望这个bug也可以解决一下。

**Comment by cxasm** [comment]
抱歉，12都不会实施。请使用vscode，那是你需要的东东。

**Comment by Jiangxp16** [comment]
> 抱歉，12都不会实施。请使用vscode，那是你需要的东东。

vscode一直在用，但一些小脚本还是用文本编辑器方便，12这两个功能npp都有，目前没发现其它编辑器实现相同功能的，也是现在使用npp的唯一理由了
