### ISSUE TITLE
文本没有换行，一般的文本编辑器都会换行

### ISSUE THREAD

**Issue by lhx24** [cxasm/notepad--#252]
![image](https://github.com/cxasm/notepad--/assets/34847496/24bd856a-8d42-4e93-907b-aa9d226d0abe)
文本没有换行，一般的文本编辑器都会换行

**Comment by cxasm** [comment]
你这是二进制文件，是在二进制模式下查看。

请使用文本方式打开。

**Comment by lhx24** [comment]
原来如此，每次都要手动切换模式。


| |
l24
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Notepad-- ***@***.***> |
| 发送日期 | 2023年10月17日 16:15 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [cxasm/notepad--] 文本没有换行，一般的文本编辑器都会换行 (Issue #252) |

你这是二进制文件，是在二进制模式下查看。

请使用文本方式打开。

**Comment by cxasm** [comment]
windows下面默认把 .obj的文件，当做二进制加载。类似还有pdf docx等都是类似的。
