### ISSUE TITLE
程序异常卡顿

### ISSUE THREAD

**Issue by zsddyd** [cxasm/notepad--#254]
在打开大文件后（27MB的txt）
1  使用右侧进度条拖动，可以上下滑动
2  点击鼠标使用光标配合PageUp,PageDown时，第一次按下会出现较长时间卡死

**Comment by cxasm** [comment]
2.9 提供了 文件缓存模式，以这种方式打开不会卡顿。
方便的话，可以加群，把该文件发出来一下，做下测试。




409652570
***@***.***



&nbsp;

**Comment by zsddyd** [comment]
目前已经是2.9版本
经过自测怀疑是打开自动换行导致
日志文件为公司业务文件，暂不方便发送
可以尝试打开自动换行功能后打开具有多个长行的文件

**Comment by cxasm** [comment]
长行文件是比较卡。如果只是查看，请使用 文件-以指定方式打开，选择最后一种方式。

**Comment by zsddyd** [comment]
了解！感谢！
