### ISSUE TITLE
能否生成一个arm64.deb以适配国产麒麟操作系统，谢谢啦

### ISSUE THREAD

**Issue by lkamh** [cxasm/notepad--#255]

**Comment by cxasm** [comment]
单位用的人多吗？最近我们新增麒麟x64的版本，但是反响平平，用户很少。

**Comment by lkamh** [comment]
> 单位用的人多吗？最近我们新增麒麟x64的版本，但是反响平平，用户很少。

也不是很多，我有个麒麟arm的大群，可以推广下，现在arm版本linux应用太少了，如果方便的话，麻烦大佬打包一个，谢谢谢谢

**Comment by cxasm** [comment]
已经发布，见https://www.123pan.com/s/DkxzVv-BwJVh.html 文件 ndd-v2.10-kinly-spv10-arm64.deb
或者见2.10 gitee发布。

**Comment by lkamh** [comment]
> 已经发布，见https://www.123pan.com/s/DkxzVv-BwJVh.html 文件 ndd-v2.10-kinly-spv10-arm64.deb 或者见2.10 gitee发布。

感谢大佬，明天我试试

**Comment by lkamh** [comment]
已测试可以使用，为表示谢意，已捐赠，万分感谢。
