### ISSUE TITLE
2.9.0版本可能存在的问题

### ISSUE THREAD

**Issue by zbc-sky** [cxasm/notepad--#268]
2.9.0版本, 单行数据文本显示是不是增加了长度限制? 因为工作原因使用了非常长的json字符串, 在没有换行的情况下, 单行显示数据不完整.
2.7.0 版本可以.

**Comment by cxasm** [comment]
更新到2.11试下。
这里应该是没改动的。

**Comment by zbc-sky** [comment]
好的

**Comment by zbc-sky** [comment]
2.11版本OK的. 多谢!
