### ISSUE TITLE
有时候用着用着字会变的不清

### ISSUE THREAD

**Issue by lkamh** [cxasm/notepad--#275]
系统是银河麒麟V10SP1
arm架构
系统版本是202303

就是平常在用的时候，突然会变成这样，字的颜色变成了白色，背景是浅紫色
![QQ20231212-085604](https://github.com/cxasm/notepad--/assets/148054779/67dd0d74-fb24-4dc0-b2b8-5dce15c11de6)
选中变成这样
![QQ20231212-090019](https://github.com/cxasm/notepad--/assets/148054779/27cc6862-0685-41b6-9f57-f59a1ea1bf29)

**Comment by cxasm** [comment]
2.11 已经解决了该问题，需要重置json语法。Json的语法，是有要求的。如果拷贝错误的非josn语法的内容到其中，则会使用错误的颜色，来标记该内容。如果你确定是json格式，才使用json语法。其他文本，建议使用txt格式。

或者手动修改josn语法中，错误的前景色即可。

**Comment by lkamh** [comment]
> 2.11 已经解决了该问题，需要重置json语法。Json的语法，是有要求的。如果拷贝错误的非josn语法的内容到其中，则会使用错误的颜色，来标记该内容。如果你确定是json格式，才使用json语法。其他文本，建议使用txt格式。
> 
> 或者手动修改josn语法中，错误的前景色即可。
好的，谢谢谢谢，那等着您更新2.11麒麟arm系统能用的
