### ISSUE TITLE
Set which syntax highlighter to use for a new file extension

### ISSUE THREAD

**Issue by yyokyfo** [cxasm/notepad--#280]
The syntax of the language is based on C# but it has the file extension `.vala`, not `.cs`. Is it possible to tell the text editor to use C#'s syntax highlighter for files with the extension `.vala`?

**Comment by cxasm** [comment]
![image](https://github.com/cxasm/notepad--/assets/42246867/9ff9a8ec-8d5a-4f1d-8ff8-e2f22f2fe339)

**Comment by yyokyfo** [comment]
It's Set -> Language File Suffix. I don't know about that. Thank you.
