### ISSUE TITLE
大佬们，注册码是自动发的吗

### ISSUE THREAD

**Issue by Xingeqwd** [cxasm/notepad--#306]
大佬们，注册码是自动发的吗，我有在备注写了邮箱，不过位置不够我没有打com。。。，

而且好像我打钱了没收到，是人工的吗。。。再等等看吧

**Comment by cxasm** [comment]
都已经发了。如果没有发，还请在gitee上加群反馈。

**Comment by Xingeqwd** [comment]
> 都已经发了。如果没有发，还请在gitee上加群反馈。

有收到，大佬，感谢大佬，大佬辛苦了！我是那天晚上发的，第二天就收到了，给力啊

**Comment by Xingeqwd** [comment]
（奇怪，好像没找到close按钮，上个回复又忘记close了，咳咳咳，close一下）
