### ISSUE TITLE
关于快捷键

### ISSUE THREAD

**Issue by thewaterislo** [cxasm/notepad--#34]
作者后面有无加入自定义快捷键的计划？个人觉得有时候习惯还是挺难改的，有时候想用了却没有，会有一丢丢的不方便。

**Comment by cxasm** [comment]
1.21.1 已经解决，自定义快捷键。

**Comment by cxasm** [comment]
![image](https://user-images.githubusercontent.com/42246867/215268743-19e13686-61dc-49fe-bbf0-2b5a652579b7.png)

**Comment by hhdqirui** [comment]
请问能加入添加和删除注释的快捷键吗？像notepad++的`Ctrl + K`。谢谢！
