### ISSUE TITLE
光标定位显示偏移，看图

### ISSUE THREAD

**Issue by baobaodu** [cxasm/notepad--#355]
Apple M1 Pro 14.0 (23A344)

随手打个括号，显示如下（看起来现在光标在括号中间）：
<img width="79" alt="image" src="https://github.com/cxasm/notepad--/assets/10076510/916dcdb7-e2ca-4b04-9e03-29de77bfa179">

但是再输入字符后，显示如下（原来刚才的光标在括号右边）：
<img width="74" alt="image" src="https://github.com/cxasm/notepad--/assets/10076510/c24f7113-85bc-4d71-bf98-097c12b5eb22">

**Comment by cxasm** [comment]
请修改对应语法文件的字体，不要使用小众字体，最好使用等宽字体，即可。

![image](https://github.com/cxasm/notepad--/assets/42246867/f9ed7d37-ee85-4dcd-95c6-12aa2d9253e3)

**Comment by baobaodu** [comment]
> 请修改对应语法文件的字体，不要使用小众字体，最好使用等宽字体，即可。
> 
> ![image](https://private-user-images.githubusercontent.com/42246867/323492012-f9ed7d37-ee85-4dcd-95c6-12aa2d9253e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjMxMDUsIm5iZiI6MTcxMzQyMjgwNSwicGF0aCI6Ii80MjI0Njg2Ny8zMjM0OTIwMTItZjllZDdkMzctZWU4NS00ZGNkLTk1YzYtMTJhYTJkOTI1M2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA2NDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNDk2OThkZGIyNWRlZmY3YTJhYTI4MzYyZTBmMWI1ODZhZjhiZDEyYzc1N2Q3ZTczNGIxZjA1YzA5MDY4OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oQzUj0BLO40wFpWhFqdn5J_m1D9fCGG873MjXfGt9jU)

谢谢，果然好了
