### ISSUE TITLE
横向滚动条异常

### ISSUE THREAD

**Issue by zhuhangit** [cxasm/notepad--#37]
> 系统：win10
> 版本：Ndd Version v1.19.1
1. 横向滚动条显示异常，也无法正常操作
1. 建议显示当前缩放比例状态
1. 快捷键定义（比如格式化）

![image](https://user-images.githubusercontent.com/32757564/210720444-7cd88e56-9d49-40b4-a554-3239487df8ab.png)

**Comment by cxasm** [comment]
更新到最新版一下。https://gitee.com/cxasm/notepad--/releases/tag/v1.20

github我不经常上，网速太慢。

**Comment by zhuhangit** [comment]
升级后1、2已解决，赞
格式化可以考虑加快捷键

**Comment by cxasm** [comment]
1.21.1 3快捷键自定义修改。
