### ISSUE TITLE
建议：自动识别文件大小，如果是大文件，使用大文件模式打开

### ISSUE THREAD

**Issue by Hoysion** [cxasm/notepad--#374]
现在是直接用notepad--打开大文件时，程序就崩溃了，希望notepad--可以自动识别文件大小，如果是大文件，使用大文件模式打开

**Comment by cxasm** [comment]
请升级到最新版本2.16一下，这个问题早就解决过了。

**Comment by Hoysion** [comment]
![image](https://github.com/cxasm/notepad--/assets/57893875/294d2f13-6eff-4730-a6f5-edf1d68711e0)
![image](https://github.com/cxasm/notepad--/assets/57893875/3f506e21-1ae8-4f7e-a9dc-ddda8cbb4ef4)
![image](https://github.com/cxasm/notepad--/assets/57893875/4f5511db-4e25-45d7-af83-cdaf1b5369c1)
![image](https://github.com/cxasm/notepad--/assets/57893875/8533e9a4-6ea2-4823-8587-f4187dc6a361)
![image](https://github.com/cxasm/notepad--/assets/57893875/b5c566b8-6bb7-4d8c-8c80-2fbbbc351611)
打开sql文件不行，打开json文件可以

**Comment by Hoysion** [comment]
好的，我更新一下版本
