### ISSUE TITLE
显示 空格./tab 过于突兀

### ISSUE THREAD

**Issue by heartacker** [cxasm/notepad--#376]
建议暗淡处理
![image](https://github.com/cxasm/notepad--/assets/1876302/a09df9fe-a3e1-48a9-8888-3dc18fb7c629)

**Comment by cxasm** [comment]
默认不开启即可，菜单还有工具栏按钮，都是有显示按钮的。图中那个 A 就是，关闭即可。

**Comment by heartacker** [comment]
我需要他开同时显示的不那么明显，而不是说关闭
