### ISSUE TITLE
文件另存为, 需要一个编码保存的选项

### ISSUE THREAD

**Issue by chifandeyu** [cxasm/notepad--#377]
这个是Notepad--的代码文件另存为
![20240619103748](https://github.com/cxasm/notepad--/assets/15946864/62f58715-5239-4a70-99b6-1a0513e7ba77)

下面这个是其他vs文件另存为的对话框:

![2024-06-19_104008](https://github.com/cxasm/notepad--/assets/15946864/a00a2533-241d-41e8-a5ab-0852fc41192d)

下面的是系统文本编辑器:
![20240619103645](https://github.com/cxasm/notepad--/assets/15946864/034e6d8a-9195-4b20-88d7-433f0cf8c06d)

**Comment by cxasm** [comment]
在界面直接选择 转换为编码即可，然后另存为。
![image](https://github.com/cxasm/notepad--/assets/42246867/3415ec67-3e3c-4772-9e78-7226f283eac9)

**Comment by chifandeyu** [comment]
> 在界面直接选择 转换为编码即可，然后另存为。 ![image](https://private-user-images.githubusercontent.com/42246867/342576154-3415ec67-3e3c-4772-9e78-7226f283eac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTY2NjQsIm5iZiI6MTcxOTM5NjM2NCwicGF0aCI6Ii80MjI0Njg2Ny8zNDI1NzYxNTQtMzQxNWVjNjctM2UzYy00NzcyLTllNzgtNzIyNmYyODNlYWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEwMDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzN2IzOWMyZWExMThlNzA1NDY1MWU4NDFjZWI1MjNiZjViYjdjNmRiN2ZjZTJhODEyZGQ2M2ZmMDQ4MmJlMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4iPF-YydVgLBIsusNGniNlmLHruCs9fRxLrjNRXXYNQ)

Ok，没想到这个位置，非常感谢你的解答
