### ISSUE TITLE
支持中共封锁境外反包反共平台GitHub，支那猪滚回墙内！

### ISSUE THREAD

**Issue by FuckXiJinPig8964** [cxasm/notepad--#378]
支那猪一天天只会意淫精神胜利，在自己的支那小圈子里自我高潮，奴隶的身份却代入赵家人的思想，支那猪的德行配得上习近平的统治。

支那猪互动热线：17573901738

《恶意人身攻击屏蔽》

翻墙软件：《恶意网址屏蔽》

**Comment by cxasm** [comment]
你可以发表意见，但是别做人身攻击和骂脏话，好吧？
做一个高素质的人，做一个脱离低级趣味的人。
