### ISSUE TITLE
请问有没有类似sublime ctrl+F2东功能

### ISSUE THREAD

**Issue by hongnod** [cxasm/notepad--#384]
现在可以高亮同样的字符串，请问有没有同时选中和编辑同样字符串的功能？

**Comment by hongnod** [comment]
VSCode中是ctrl+shift+L

**Comment by cxasm** [comment]
不支持。Ndd编辑的文本可能很大，一个字段可能有几千上万都是可能的。而vsc只是编辑代码文件，往往很小，使用场景不同。
