### ISSUE TITLE
Win11 在双屏幕, 并且分辨率和缩放比例都不一致时, 出现tap标签字体异常

### ISSUE THREAD

**Issue by 1311502563** [cxasm/notepad--#385]
![QQ截图20240701153849](https://github.com/cxasm/notepad--/assets/55420269/200459ca-19ed-44a4-9b05-6e8d122f6d6b)
如图, 字体变得非常小
两个屏幕的设置如图
2k屏幕150%缩放, 1080p100%缩放
![QQ截图20240701154038](https://github.com/cxasm/notepad--/assets/55420269/6938d8a2-1fe8-4ecb-b1d6-bf414938c857)

![QQ截图20240701154103](https://github.com/cxasm/notepad--/assets/55420269/05690e95-7a0d-447d-84b8-9f34fc9c0d59)

**Comment by cxasm** [comment]
调大界面字体。看看手册，或者摸索一下。

![image](https://github.com/cxasm/notepad--/assets/42246867/6630c83a-c12d-45c8-ac12-8cef4b9ff14e)

**Comment by 1311502563** [comment]
非常感谢, 已经解决了, 在重启电脑后重新设置一次缩放比例, 此问题不再出现
