### ISSUE TITLE
自动换行模式问题

### ISSUE THREAD

**Issue by deepseer** [cxasm/notepad--#387]
现在的文本编辑软件常见的自动换行有两种，一种是无视内容只看长度直接换行（notepad--当前是这样），一种是根据内容（比如空格、标点）智能换行（notepad++当前是这样）。
两种方式各有优缺点。
直接换行：会拆开英文单词。
智能换行：中英文混排的时候大段中文会被识别为一个单词，不会在汉字间换行。

还有最高级的智能换行：类似word，结合以上两者优点。

能否改进一下换行功能，至少是增加切换换行方式的选项？

**Comment by cxasm** [comment]
右键，按单词换行（英文）按汉字换行（中文），自行切换即可，在2.14就支持了。

![image](https://github.com/cxasm/notepad--/assets/42246867/fbaa7765-dfb6-4179-9e82-17f48ed22c4a)
