### ISSUE TITLE
UI有点小

### ISSUE THREAD

**Issue by ZKENSS** [cxasm/notepad--#410]
能不能加大点，笔记本上看着有些难受。

**Comment by ZKENSS** [comment]
指的是图标上面那一行
文件，编辑，查找……

**Comment by cxasm** [comment]
调大字体。请使用2.17之后版本。
![image](https://github.com/user-attachments/assets/a16473a6-6ac1-4457-9047-3692ee162979)

**Comment by ZKENSS** [comment]
感谢
