### ISSUE TITLE
你好，冒昧问一下是否有支持base64转换的想法？

### ISSUE THREAD

**Issue by izsiyy** [cxasm/notepad--#42]
你好，冒昧问一下是否有支持base64转换的想法？

**Comment by cxasm** [comment]
这是一个很简单，很小的功能，支持没有问题。
但是好像不是大众功能。后续可以提供一个小插件，解决该问题。

**Comment by izsiyy** [comment]
谢谢ヾ(≧∇≦谢谢≧∇≦)ノ
