### ISSUE TITLE
显示选中字符的字符数和字节长度

### ISSUE THREAD

**Issue by bingoguo93** [cxasm/notepad--#43]
能否支持在右下角显示选中字符的字符数和字节长度
![image](https://user-images.githubusercontent.com/37023599/215124772-3906d0e3-945d-4747-90ca-0972cdd491b8.png)

![image](https://user-images.githubusercontent.com/37023599/215125751-a6861d9f-ce7c-450b-8a7d-063541fc3606.png)

**Comment by cxasm** [comment]
已经知晓。但是下面状态栏，已经够拥挤了。
这个功能，可以提供一个右键菜单来做。现在需求反馈的不是太多。

**Comment by bingoguo93** [comment]
1.23看到已经加入了
