### ISSUE TITLE
新建文件，没有执行保存，下次重新打开，不是上次退出的当前标签，每次都要找一圈才能找到，而且偶尔文字还会丢失。

### ISSUE THREAD

**Issue by tianmy** [cxasm/notepad--#431]
版本：Ndd Version v1.21.0
新建文件，没有执行保存，下次重新打开，不是上次退出的当前标签，每次都要找一圈才能找到，而且偶尔文字还会丢失。

**Comment by cxasm** [comment]
升级到2.18版本一下。 我经常无法访问github，回复不会太及时。

**Comment by cxasm** [comment]
升级到2.20.1一下，早解决过了。
