### ISSUE TITLE
全局一键设置字体的问题

### ISSUE THREAD

**Issue by waruqi** [cxasm/notepad--#44]
试了下全局风格设置，我仅仅只是想设置字体，但是会一并篡改掉代码的颜色配置。

我单独设置每个语言的字体，只能挨个 keywork/string。。设置，很繁琐，而且中途遇到一些 bug，会经常丢失已有的颜色，变成黑色。

有没有方便一键设置字体（任意代码字体都强制修改成相同的），其他的（颜色等）都不改的方式？

**Comment by cxasm** [comment]
是的，1.20之前有这个问题。请升级到1.21版本。国内从gitee下载速度更快。

**Comment by waruqi** [comment]
用的就是 1.21.1 今天刚下载的，macOS 版本

**Comment by cxasm** [comment]
我在win10下面没有复现该问题，mac的我后续会看看。
如果你修改的是全局字体，则要勾选 使用全局字体大小；而不能 勾选 全局前景颜色，否则会把颜色也修改了。

我刚刚试过了，单纯修改大小，不会修改颜色。另外，如果修改错误了，你 点击 重置，就能恢复到软件最开始的默认状态。

![image](https://user-images.githubusercontent.com/42246867/215267265-37776f27-6160-4d92-8f35-2cb0b2a1cab6.png)

**Comment by waruqi** [comment]
我仅仅勾了这两

<img width="151" alt="image" src="https://user-images.githubusercontent.com/151335/215267536-7299564f-5e3f-45c9-8cc6-b06669e588b4.png">

除了这个全局设置，单个语言的字体设置，有时候也会有这个问题，改 c/c++comment/string 挨个改，改到中途 随机性 颜色会变黑。。（可能是我没点保存导致，后来我挨个改，每改一个，点一下保存 似乎改好了）

**Comment by waruqi** [comment]
> 如果你修改的是全局字体，则要勾选 使用全局字体大小；而不能 勾选 全局前景颜色，否则会把颜色也修改了。

刚试了下，全局那个可以了，没法复现，可能一开始是我操作不当，我先关了。谢谢
