### ISSUE TITLE
光标附近不能显示中英文

### ISSUE THREAD

**Issue by xiaoxin6182** [cxasm/notepad--#443]
https://github.com/abgox/InputTip/issues/61
这个项目提到了notepad--，正好2个软件我都在使用，顺便测试了一下notepad++（它是正常的），希望notepad--可以优化一下。

notepad++显示效果
![notepad++测试效果](https://github.com/user-attachments/assets/718f07b9-f7b5-43b3-be42-b3c1b99cbd5e)

notepad--显示效果
![notepad--测试效果](https://github.com/user-attachments/assets/d7e7dee1-739c-4fd1-99c9-d18b85e164d0)

InputTip设置
![InputTip设置](https://github.com/user-attachments/assets/5c719b26-0cb3-4fff-83c2-c4219a0ebbfc)

**Comment by cxasm** [comment]
不太情况该外挂软件。不建议使用外挂软件，会导致系统不稳定。
