### ISSUE TITLE
求：“选中一个字或词”即自动选中所有相同的自或词。能不能取消这个设置

### ISSUE THREAD

**Issue by PerryLayne** [cxasm/notepad--#448]
很好的文本工具，很轻便，很实用，目前找到的唯一能标记的笔记。
但是我选择一个词后，比如选中“好的”，就自动选中文本中所有的“好的”
这样让我的标记无法进行，我找了选项里每一个设置。好像并没有，有办法取消吗

**Comment by cxasm** [comment]
我经常无法访问github，回复不会及时。

你说的应该是这个选项，在2.19或2.20中有，勾选关闭即可。

![image](https://github.com/user-attachments/assets/2469f9fb-0e96-4136-9cbf-5d2c3f4b6dad)

**Comment by PerryLayne** [comment]
> 我经常无法访问github，回复不会及时。
> 
> 你说的应该是这个选项，在2.19或2.20中有，勾选关闭即可。
> 
> ![image](https://private-user-images.githubusercontent.com/42246867/374816159-2469f9fb-0e96-4136-9cbf-5d2c3f4b6dad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDg5NzQsIm5iZiI6MTcyODcwODY3NCwicGF0aCI6Ii80MjI0Njg2Ny8zNzQ4MTYxNTktMjQ2OWY5ZmItMGU5Ni00MTM2LTljYmYtNWQyYzNmNGI2ZGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA0NTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OGJiZjc2MTQxYTM1OWJlYjdkNjdiNjMwMTY0YzQ1YmQzNmY5OTdiODdiMmY0MjQ3OGFmY2MzMzQzNjMwMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yhOJKa9MGqiftuPaqCmpd_XlZQcWseyRX8ieYD16Dh0)

非常感谢解答，我之前用的是Github能下载到的2.18，我区Gitee下载了2.20，这样设置确实不会高亮显示了

但是仍然在选中高亮时高亮了所有的选中词
我需要只高亮选中的词，请问可以做到吗？
