### ISSUE TITLE
格式换行问题

### ISSUE THREAD

**Issue by kof8855** [cxasm/notepad--#459]
比如我经常要编辑pac.txt文件，添加域名代理，用notepad++增加逗号回车之后，他会自动按格式下一行帮我留空到对应的格式
而--回车之后直接是换行在首行顶，不会按格式帮我添加空格

![image](https://github.com/user-attachments/assets/bdd2fc6c-7b91-4206-8be3-dc6ff3fa934d)

**Comment by cxasm** [comment]
有这个功能，可能默认是关闭的，需要开启一下。有些用户不知道，反而认为这个功能是bug，所以做了一个开关。
如果需要，勾选即可。
![image](https://github.com/user-attachments/assets/3c0b03c3-e7ad-440f-bd57-0b84291158bf)

**Comment by kof8855** [comment]
> 有这个功能，可能默认是关闭的，需要开启一下。有些用户不知道，反而认为这个功能是bug，所以做了一个开关。 如果需要，勾选即可。 ![image](https://private-user-images.githubusercontent.com/42246867/381818693-3c0b03c3-e7ad-440f-bd57-0b84291158bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNTAyNjYsIm5iZiI6MTczMDM0OTk2NiwicGF0aCI6Ii80MjI0Njg2Ny8zODE4MTg2OTMtM2MwYjAzYzMtZTdhZC00NDBmLWJkNTctMGI4NDI5MTE1OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA0NDYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MTRhMDBjYWY0MjlkMGI4MTFkNmZmZTg3NGFkZjNhZTg2ZDJiNWM5M2I3NDVjNTRhYTQxYWNkMDgxMjBkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2ysLLVighwxWoUszpp-WoYQr2r7JS_SQc3tfTIjenUA)

可以了，感谢
