### ISSUE TITLE
When will it be like Atom or like Eclipse?

### ISSUE THREAD

**Issue by dingymmm** [cxasm/notepad--#46]
When will it be like Atom or like Eclipse? How do I explain that the document is in simplified Chinese? Not the same as notepad -- internationalization? See the front is not yet notepad ++ perfect?

**Comment by dingymmm** [comment]
请问是否添加插件功能，项目的说明文档怎么是简体中文？难道要像不想往国际化发展吗？notepad ++ 作者会不会告你抄袭？

**Comment by mczph** [comment]
他管得着？

**Comment by cxasm** [comment]
抱歉，永远不会像 atom 或者 eclipse，我们不做大的ide，也不主要为编程人服务。
我们的出发点，就是不做ide，做小 而轻快的 文本编辑器。

**Comment by cxasm** [comment]
> 

另外，目前1.21已经可以编写插件。我们就在中国先发展，站稳再说。
n++的作者没法告我，因为我是基于qt/cpp做的，是一个全新的东西。请你不要以为，我们只是fork了一份npp的代码，这样想的话，真是太瞧不起人了。
我们是一个全新的东西，基于qscint内核，全平台的东西，如果就是fork一份npp的代码，那我们是怎么能够支持mac linux uos 等系统的呢？ndd是可以支持 mac ubuntu uos 等系统的。现在的中国，大把的能人，一大堆可以写编译器、编辑器、甚至微内核的人，不要觉得国人的水平就只能抄袭。ok ？

**Comment by mczph** [comment]
支持

**Comment by dingymmm** [comment]
> > 
> 
> 另外，目前1.21已经可以编写插件。我们就在中国先发展，站稳再说。 n++的作者没法告我，因为我是基于qt/cpp做的，是一个全新的东西。请你不要以为，我们只是fork了一份npp的代码，这样想的话，真是太瞧不起人了。 我们是一个全新的东西，基于qscint内核，全平台的东西，如果就是fork一份npp的代码，那我们是怎么能够支持mac linux uos 等系统的呢？ndd是可以支持 mac ubuntu uos 等系统的。现在的中国，大把的能人，一大堆可以写编译器、编辑器、甚至微内核的人，不要觉得国人的水平就只能抄袭。ok ？

ok，挺好的，我也在撸一个在线版本ide :)

![image](https://user-images.githubusercontent.com/38412458/215269946-a71621f6-b7d9-4173-a5d5-10171f26ebd1.png)
