### ISSUE TITLE
保存上次打开的目录

### ISSUE THREAD

**Issue by liuyug** [cxasm/notepad--#461]
上次关闭前打开的目录不能保存位置

新开启 Notepad-- 默认不能恢复上次打开的目录，功能类似恢复上次打开的文件。

**Comment by cxasm** [comment]
已经有该功能，默认没开启，在设置中开启即可。

选项-保存与恢复-记住最后打开的文件夹，勾选即可。

![Uploading image.png…]()

**Comment by liuyug** [comment]
看到了，谢谢
