### ISSUE TITLE
如何将多行转换成字符串，合并成一行

### ISSUE THREAD

**Issue by 2416210017** [cxasm/notepad--#467]
为什么使用\r\n不生效，在notepad++中是可以的，请问怎么合并成一行？
![image](https://github.com/user-attachments/assets/b01f08f0-0de5-4105-8fea-7ab648c41eb5)
![image](https://github.com/user-attachments/assets/cae85551-ea85-422b-8778-74bf9cace45b)
最终效果
![image](https://github.com/user-attachments/assets/d1fba349-ca44-4068-b7c3-46a6b7a86af6)

**Comment by dislyte001** [comment]
查看目标 \r  
替换为
替换所有打开文件
完成

**Comment by 2416210017** [comment]
> 查看目标 \r 替换为 替换所有打开文件 完成
没有用，是哪里不对吗？
![image](https://github.com/user-attachments/assets/0c3f2157-a936-41f9-b2ce-439064e5dba4)

**Comment by cxasm** [comment]
看看2.20说明书。macos 下面换行符不是\r\n 而是 \n

**Comment by 2416210017** [comment]
> 看看2.20说明书。macos 下面换行符不是\r\n 而是 \n

感谢解答😊
