### ISSUE TITLE
大佬，建议出个windows安装版本的，安装后直接右键通过软件打开，一个个关联后缀实在太麻烦了

### ISSUE THREAD

**Issue by sl-w** [cxasm/notepad--#5]

**Comment by sl-w** [comment]
感谢大佬指点，建议写到readme中，让更多小白看到






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月5日(星期一) 晚上10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cxasm/notepad--] 大佬，建议出个windows安装版本的，安装后直接右键通过软件打开，一个个关联后缀实在太麻烦了 (Issue #5)





 
可以的，最近就出一个windows下的安装版本。
 
目前windows下其实不需要一个一个关联。
 
1）你只需要把 Notepad--放在一个固定位置，然后不要移动程序位置。
 2）找到notepad--的位置，右键，以管理员权限运行，运行一次后，就会把当前右键位置注册到右键菜单中区。
 只需要这样执行一次后，windows下就自动关联所有文件了。
 
 
如果你每次移动了notepad--位置，都要以管理员权限运行一次即可。

**Comment by cxasm** [comment]
已经除了一个测试版的win10安装版本。

**Comment by cxasm** [comment]
可以的。


目前不需要一个一个关联。
1）你只需要把 Notepad--放在一个固定位置，然后不要移动位置。
2）以找到notepad--的位置，右键，以管理员权限运行，运行一次后，就会把当前右键位置注册到右键菜单中区。
只需要这样执行一次后，windows下就自动关联所有文件了。



如果你每次移动了notepad--位置，都要以管理员权限运行一次即可。




爬山虎
***@***.***



&nbsp;
