### ISSUE TITLE
打开yaml格式文件乱码

### ISSUE THREAD

**Issue by sunzqe** [cxasm/notepad--#6]
大佬，为啥打开yaml文件格式乱码，OS:macos
![1662600527062](https://user-images.githubusercontent.com/20399909/189013424-8a115c34-3263-4728-b5c4-c66392215720.jpg)

**Comment by cxasm** [comment]
这是按照16进制格式打开了。因为软件检测到该文件可能是二进制。
两个解决方式。1）右键文件标签，重新以文本模式打开。可以解决。

2）永远解决办法：在选项文件关联中，把后缀yaml的自定义添加到关联中去。下次遇到yaml的文件，软件会自动识别
为文本模式。

**Comment by sunzqe** [comment]
解决了，谢谢大佬

**Comment by cxasm** [comment]
win10 1.15安装版本已经彻底解决了该问题。
