### ISSUE TITLE
win端，为什么我打开普通的文本文件(.pdb后缀)，会被识别为二进制文件？

### ISSUE THREAD

**Issue by AaranWang** [cxasm/notepad--#68]
有没有方法避免？这是因为软件自动识别的原因吗，语法关联那里并没有找到以pdb格式结尾的语法，所以也没办法删除或更改；我还尝试在语法关联里，在txt语法后，加入.pdb格式，但是依旧没用

**Comment by cxasm** [comment]
pdb一般是二进制格式的。
![image](https://user-images.githubusercontent.com/42246867/215753050-523af229-0517-42f3-9796-f67fef0f8957.png)

**Comment by AaranWang** [comment]
我的pdb格式是生物学里的数据格式，是txt格式，怎样设置可以默认把pdb格式读成txt呢？你图里回复这个我看到了，但是每次打开文件都要重新操作“以文本模式打开”，有没有一下设置好，每次重启都没问题的办法？谢谢开发大大。湾湾永远都是中国的！

**Comment by cxasm** [comment]
好的。我会解决。

**Comment by AaranWang** [comment]
谢谢开发大大，我等你的更新版本

**Comment by cxasm** [comment]
1.22 版已经发布了一个。还请更新。
如果pdb本身是一个文本，则可以打开。

**Comment by AaranWang** [comment]
简直是火速啊，支持支持！

**Comment by cxasm** [comment]
1.22.1已经发布，已经支持。
