### ISSUE TITLE
增加超链接功能

### ISSUE THREAD

**Issue by ZhangYangyong** [cxasm/notepad--#73]
作者大大,能否在后续版本中添加超链接功能,实现在文本内超链接有下划线提示(可开启或关闭),ctr+单击直接调用浏览器访问的功能

**Comment by cxasm** [comment]
已经有这个功能了。在视图里面，显示网站。不推荐开启。

**Comment by zhaobudaomingzi** [comment]
> 已经有这个功能了。在视图里面，显示网站。不推荐开启。

请问一下作者，为什么不建议开启，开启之后有什么影响吗？
