### ISSUE TITLE
建议叫notepad#，--在气势上感觉比++低了一等似的！

### ISSUE THREAD

**Issue by Webdiyer** [cxasm/notepad--#79]

**Comment by cxasm** [comment]
现在已经是这样了，后续会推出一个另外的精简版本。

**Comment by jingslunt** [comment]
> 现在已经是这样了，后续会推出一个另外的精简版本。

可以考虑贡献给字节开源组

**Comment by townechow** [comment]
> > 现在已经是这样了，后续会推出一个另外的精简版本。
> 
> 可以考虑贡献给字节开源组

字节会去碰这坨臭屎？？？

**Comment by sgf** [comment]
除了气势原创内容是什么? 虽然,湾湾作者的政治取向有问题,但是不可否认npp是个不错的开源软件.
不是谁都可以被替代的,这本身也说明了实力.至于本项目能否长久生存,不可知也.

**Comment by cxasm** [comment]
感谢您的反馈。大厂瞧不上，小厂做不了，这是国产的尴尬。

**Comment by yangsongx** [comment]
那就草根来慢慢搞吧，还是需要时日的

我第1次知道有N++是2005年，那年的4月份获得Sourceforge的Project of the Month荣誉
