### ISSUE TITLE
菜单的字体是行书 

### ISSUE THREAD

**Issue by iwakaka** [cxasm/notepad--#8]
![image](https://user-images.githubusercontent.com/21689019/190110460-790f1c87-81ab-4425-826c-d79e83184551.png)

win11系统 
v1.15版
行书看着有点膈应

**Comment by cxasm** [comment]
已经收到了，下个版本会更正。
win10默认字体是"SimSun,9,-1,5,50,0,0,0,0,0"。可能win11系统默认不一样。
下个版本会以微软雅黑做默认字体。同时在选项中提供程序字体的设置功能。

**Comment by cxasm** [comment]
请重新试一下这个新出的包。https://gitee.com/cxasm/notepad--/releases/download/v1.15/Notepad--v1.15.2-x64-setup.exe
在win11下面会自动检查三种字体，SimSun、Courier、Times New Roman。
只有三种存在只有，界面都可以正常显示。
如果三种字体都不存在，则需要在windows里面安装一下三种字体中的任意一种字体即可。

**Comment by iwakaka** [comment]
> 最新版https://github.com/cxasm/notepad--/releases/tag/notepad-v1.16 在win11上还存在这个问题吗？

呃呃呃。。。试了一下就卸载了。一直用的notepad3，然而notepad3就是不肯支持多标签
