### ISSUE TITLE
先反馈3点问题

### ISSUE THREAD

**Issue by ztdawang** [cxasm/notepad--#81]
1、要能隐藏菜单栏，文本编辑器越简洁越好。或者把最上方的文件名一栏+菜单栏+最大化窗口那些合并成一行
2、右下角状态栏，无法双击修改语言的语法 和 windows CR LF改为Unix
3、显示行数的 这个黑灰色 有点丑，  New 0 和 New 1 这种字体和大小都不太美观

总之，做成跟Notepad3一样好看，再加一个 多标签页 功能就行了
![image](https://user-images.githubusercontent.com/22386267/215983061-e8ed8c7b-aefa-43ed-9643-ce39f4b6e924.png)

**Comment by cxasm** [comment]
1 和 2 都是有的，在视图里面。
3 字体细节，需要完善，后续主要问题解决后，肯定会完善这些。

**Comment by cxasm** [comment]
1.22.1 已经发布。
上面3个问题，都已经解决。行号颜色，本来就是可以自行调整的，见下图。
换行也做了快捷选择。

![image](https://user-images.githubusercontent.com/42246867/217143963-98011a1c-bb56-4d31-9204-805ebf2682f7.png)
