### ISSUE TITLE
[BUG]同一个CSV文件--打开只有100多行，用++打开正常6w多行

### ISSUE THREAD

**Issue by chinaxushi** [cxasm/notepad--#86]
同一个CSV文件--打开只有100多行，用++打开正常6w多行

如果作者需要这个文件，我可以发给你。

**Comment by cxasm** [comment]
系统有个设置，超过100M的文件，会以只读分块模式打开。
需要手动进行前后翻页。如果您觉得该文件要一次性加载，可以把值变大。

大文件比例避免加载慢，只能分块加载，手动翻页处理。

好的，您可以把这个文件发给我复现一下。
![image](https://user-images.githubusercontent.com/42246867/216488757-218b94c7-072d-4b65-8476-95bf5991e9a8.png)

![image](https://user-images.githubusercontent.com/42246867/216489090-fb6327fa-1449-478d-99c0-66817236c9b7.png)

![image](https://user-images.githubusercontent.com/42246867/216489142-50080e9f-7258-4c6b-9968-999744046c64.png)

**Comment by cxasm** [comment]
请更新到1.22版本，我们提供了最新版本。

**Comment by chinaxushi** [comment]
> 请更新到1.22版本，我们提供了最新版本。



> 系统有个设置，超过100M的文件，会以只读分块模式打开。 需要手动进行前后翻页。如果您觉得该文件要一次性加载，可以把值变大。
> 
> 大文件比例避免加载慢，只能分块加载，手动翻页处理。
> 
> 好的，您可以把这个文件发给我复现一下。 ![图像](https://user-images.githubusercontent.com/42246867/216488757-218b94c7-072d-4b65-8476-95bf5991e9a8.png)
> 
> ![图像](https://user-images.githubusercontent.com/42246867/216489090-fb6327fa-1449-478d-99c0-66817236c9b7.png)
> 
> ![图像](https://user-images.githubusercontent.com/42246867/216489142-50080e9f-7258-4c6b-9968-999744046c64.png)

文件大小并不大，只有10多兆，新版1.22我也已经试了，还是打开只有300多行（前面说错了，打开时300多行），文件我怎么发你呢，给个邮箱？

**Comment by cxasm** [comment]
发吧。发给我看看。 757210195@qq.com

**Comment by chinaxushi** [comment]
> 757210198@qq.com

已发送。

**Comment by cxasm** [comment]
文件里面有乱码，直接截断了，我后续会修正该问题。

![image](https://user-images.githubusercontent.com/42246867/216548104-5347afb3-dc75-43b1-b2f5-5b9409dc1aa6.png)

**Comment by cxasm** [comment]
下个版本1.22.1解决。尽量让乱码也打印出来吧。
之前我们发现有乱码，就直接不加载后续内容了，觉得显示也看不懂。

**Comment by yangjinhaoaa** [comment]
公司拿来看串口log的，串口文件前几行经常会有一大片乱码。然后notepad--就会识别成二进制文件，我用文本打开也是只读模式，不能**查找** 编辑。
主要是查找功能，找不到关键字就没法看log了

**Comment by yangjinhaoaa** [comment]
> 下个版本1.22.1解决。尽量让乱码也打印出来吧。
> 之前我们发现有乱码，就直接不加载后续内容了，觉得显示也看不懂。

我这里经常有很大的文本格式的串口log上百兆的，300兆的限制还是不大够的感觉😂

还有上条评论中说的文本文件前半部分有乱码导致识别成二进制文件的问题，经常有这种部分乱码文件要打开，这样弹出来一个窗口还是影响体验的。
如果需要复现问题的文件我可以尽量提供。感谢作者😉

**Comment by cxasm** [comment]
1.23 版本会提供查找。但是文件大了，查找会非常慢。只能支持一个一个挨个查找。

1.22.1 马上会发布，会优化乱码一部分问题。乱码可能是编码不对，需要自己设置文件的编码。

**Comment by yangjinhaoaa** [comment]
> 1.22.1 马上会发布，会优化乱码一部分问题。乱码可能是编码不对，需要自己设置文件的编码。

🐂🍺
非常感谢！期待新版本的到来

**Comment by cxasm** [comment]
1.22.1 已经发布，还请更新测试。感谢反馈。

**Comment by cxasm** [comment]
> > 下个版本1.22.1解决。尽量让乱码也打印出来吧。
> > 之前我们发现有乱码，就直接不加载后续内容了，觉得显示也看不懂。
> 
> 我这里经常有很大的文本格式的串口log上百兆的，300兆的限制还是不大够的感觉😂
> 
> 还有上条评论中说的文本文件前半部分有乱码导致识别成二进制文件的问题，经常有这种部分乱码文件要打开，这样弹出来一个窗口还是影响体验的。 如果需要复现问题的文件我可以尽量提供。感谢作者😉

麻烦给我发一个样本文件。我会在1.23中继续优化该问题。提供查找功能。

**Comment by cxasm** [comment]
请使用ndd2.2版本，已经可以支持一次性加载，滑动查看大文件了。目前测试100G是没有问题的。
