### ISSUE TITLE
从windows命令行用notepad--打开一个相对路径文件提示文件不存在

### ISSUE THREAD

**Issue by jiancaihao** [cxasm/notepad--#89]
从windows命令行，用notepad--打开一个文件，路径用相对路径给出，notepad--窗口打开， 提示文件不存在，例如：
D:\work\test>notepad-- test.c
则打开notepad--窗口，但弹出错误提示窗口：”文件 test.c 不存在“

**Comment by cxasm** [comment]
已经知晓。下个版本1.22.1会解决。

**Comment by cxasm** [comment]
1.22.1 已经发布，还请更新测试。感谢反馈。

**Comment by lcw0622** [comment]
@cxasm 现在是还不支持通过命令行打开目录，然后左侧自动展示目录列表么
