### ISSUE TITLE
伪开源

### ISSUE THREAD

**Issue by cyh-ustc** [cxasm/notepad--#9]
rt

**Comment by cxasm** [comment]
现在还不是开源的时候。当如下三个条件满足一个时，会开源。
1）已经在windows uos mac 三系统彻底打败notepad++，完全占领市场时。
2）代码规模和难度大到就算放出来，大家也吃不透时。
3）用户付费购买源代码时。

国内的程序员内卷太严重了，不想让同行更加内卷，如果都完全免费，互相抄袭，最后程序员同行都会完蛋。
不开源是为了不内卷，提高国内程序员的价值。

**Comment by peiyingyao** [comment]
“国内的程序员内卷太严重了，不想让同行更加内卷，如果都完全免费，互相抄袭，最后程序员同行都会完蛋。
不开源是为了不内卷，提高国内程序员的价值。”
你凭啥认为别人跟你一样也是抄别人的？
