### ISSUE TITLE
棕色的背景色对看文本而言是极其糟糕的

### ISSUE THREAD

**Issue by hzz1189** [cxasm/notepad--#91]
能否跟以前一样统一用白色背景色就好？
![1](https://user-images.githubusercontent.com/51041656/216911680-f90732bd-50dd-491d-89b8-a6312e52e3b5.png)
![2](https://user-images.githubusercontent.com/51041656/216911699-de7510f5-0dc5-4db8-86c0-121cba77a057.png)

**Comment by cxasm** [comment]
把图中右下角 重置 按钮 点击一下。1.20 到 1.21 有个过渡，中间配色需要重置。
新安装版本不会有为。

**Comment by hzz1189** [comment]
我试了一下重置，发现只对当前后缀文件有效，这样就太麻烦了，希望可以简单地一劳永逸解决，如果说新安装的版本不会有问题，是否我卸载重装就可以了？

**Comment by cxasm** [comment]
其实是有全局重置的。下面是1.22.1的。1.21类似，不过没有单独 全局设置按钮。

请使用1.22.1版本，全局设置单独提出了。

![image](https://user-images.githubusercontent.com/42246867/217143215-894dc272-73e3-44a9-89f9-3a160711d5fa.png)

**Comment by cxasm** [comment]
请升级到1.23.2版本。重置样式，或者自行修改为喜欢的背景色。
