### ISSUE TITLE
为什么菜单项总是在后面多一个(F)之类的快捷提示，感觉很不协调

### ISSUE THREAD

**Issue by yangsongx** [cxasm/notepad--#93]
为什么File(F), Edit(E)

一般都是直接在File的F下面做下划线，感觉这样不协调，N++倒是没这样，

个人的建议哈

**Comment by cxasm** [comment]
NDD是中文界面。

**Comment by yangsongx** [comment]
谢谢回复，

![image](https://user-images.githubusercontent.com/836768/217154607-b1534b9b-6e16-43aa-aaf4-d286ae83ad9d.png)

可以建议适配下 英文版么？

**Comment by yangsongx** [comment]
Already raised PR and merged into master, hope can see it soon on github
