### ISSUE TITLE
闪退未自动保存导致内容丢失

### ISSUE THREAD

**Issue by Doooing** [cxasm/notepad--#97]
版本：

macos 13.0.1 (22A400)
nd-- 1.2.1

操作：
两个窗口两个文件, 一个txt正在编辑文本，另一个窗口打开快捷键管理页面，在已开启周期性保存的情况下，闪退，导致之前写好的内容丢失, 如下图
<img width="1381" alt="sp20230208_232620_642" src="https://user-images.githubusercontent.com/58727869/217575908-28089b40-ffc9-4986-807b-b7681f479b44.png">

建议：
感觉这个情况还是挺伤的，不敢肆无忌惮的编辑了，写两下就得保存一下，没有安全感，希望大佬能优化下这个

另外，有一个问题，周期性保存是多久自动保存一次呢？

**Comment by cxasm** [comment]
感谢反馈。mac之前用户比较少，问题暴露还不充分。
我们会不断改进Ndd在mac上面的稳定性和效果。
