### ISSUE TITLE
清除历史打开文件时闪退

### ISSUE THREAD

**Issue by Doooing** [cxasm/notepad--#98]
![sp20230208_234349_356](https://user-images.githubusercontent.com/58727869/217578672-1ae7711c-6528-416b-8cb1-1f95aa26e619.png)

清除历史打开文件时, 又闪退, 并且之前重新打开后, 之前已经编辑并保存好的新内容丢失(可以参考[上一个issues](https://github.com/cxasm/notepad--/issues/97), 其中有新编辑好的文件截图)

以下是意外退出的问题报告: 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Notepad-- [3246]
Path:                  /Applications/Notepad--.app/Contents/MacOS/Notepad--
Identifier:            www.itdp.cn.Notepad--
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-02-08 23:40:05.4645 +0800
OS Version:            macOS 13.0.1 (22A400)
Report Version:        12
Bridge OS Version:     7.0 (20P420)
Anonymous UUID:        769F9CF1-8B16-6607-C41A-1981E205D39F

Time Awake Since Boot: 5100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000020730e633350
Exception Codes:       0x0000000000000001, 0x000020730e633350

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [3246]

VM Region Info: 0x20730e633350 is not in any region.  Bytes after previous region: 35673608717137  Bytes before following region: 69874581556400
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      CoreAnimation               125559000-1259cb000    [ 4552K] rw-/rwx SM=PRV  
--->  GAP OF 0x5ffeda635000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Notepad--                     	       0x107c69df5 CCNotePad::slot_clearHistoryOpenList() + 133
1   QtCore                        	       0x109dcad0c QMetaObject::activate(QObject*, int, int, void**) + 3132
2   QtWidgets                     	       0x10877e015 QAction::activate(QAction::ActionEvent) + 309
3   QtCore                        	       0x109dc33c1 QObject::event(QEvent*) + 753
4   QtWidgets                     	       0x10878765d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
5   QtWidgets                     	       0x108788a01 QApplication::notify(QObject*, QEvent*) + 497
6   QtCore                        	       0x109d999a4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
7   QtCore                        	       0x109d9abde QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 878
8   libqcocoa.dylib               	       0x1095f6b19 0x1095c0000 + 224025
9   libqcocoa.dylib               	       0x1095f7288 0x1095c0000 + 225928
10  CoreFoundation                	    0x7ff80e8e0bc8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
11  CoreFoundation                	    0x7ff80e8e0b77 __CFRunLoopDoSource0 + 157
12  CoreFoundation                	    0x7ff80e8e0951 __CFRunLoopDoSources0 + 212
13  CoreFoundation                	    0x7ff80e8df5cb __CFRunLoopRun + 929
14  CoreFoundation                	    0x7ff80e8debb0 CFRunLoopRunSpecific + 560
15  HIToolbox                     	    0x7ff8181c0bd6 RunCurrentEventLoopInMode + 292
16  HIToolbox                     	    0x7ff8181c0806 ReceiveNextEventCommon + 199
17  HIToolbox                     	    0x7ff8181c0723 _BlockUntilNextEventMatchingListInModeWithFilter + 70
18  AppKit                        	    0x7ff811a01b37 _DPSNextEvent + 909
19  AppKit                        	    0x7ff811a009b8 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
20  AppKit                        	    0x7ff8119f2ff3 -[NSApplication run] + 586
21  libqcocoa.dylib               	       0x1095f6003 0x1095c0000 + 221187
22  QtCore                        	       0x109d94f8f QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
23  QtCore                        	       0x109d99fb2 QCoreApplication::exec() + 130
24  Notepad--                     	       0x107bd791c main + 1004
25  dyld                          	    0x7ff80e4d5310 start + 2432

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff80e7c76a2 mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80e7d567d mach_msg2_internal + 82
2   libsystem_kernel.dylib        	    0x7ff80e7ce71a mach_msg_overwrite + 723
3   libsystem_kernel.dylib        	    0x7ff80e7c7989 mach_msg + 19
4   CoreFoundation                	    0x7ff80e8e0d0e __CFRunLoopServiceMachPort + 145
5   CoreFoundation                	    0x7ff80e8df77a __CFRunLoopRun + 1360
6   CoreFoundation                	    0x7ff80e8debb0 CFRunLoopRunSpecific + 560
7   AppKit                        	    0x7ff811b61696 _NSEventThread + 132
8   libsystem_pthread.dylib       	    0x7ff80e806259 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff80e801c7b thread_start + 15

Thread 2:: QThread
0   libsystem_kernel.dylib        	    0x7ff80e7ce3ba poll + 10
1   QtCore                        	       0x109df0130 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 608
2   QtCore                        	       0x109df1927 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 903
3   QtCore                        	       0x109d94f8f QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
4   QtCore                        	       0x109bd036c QThread::exec() + 140
5   QtCore                        	       0x109bd12e3 0x109baf000 + 140003
6   libsystem_pthread.dylib       	    0x7ff80e806259 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff80e801c7b thread_start + 15

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff80e801c58 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	    0x7ff80e801c58 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff80e801c58 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000020730e633330  rbx: 0x00006000022bb060  rcx: 0x0000000000000001  rdx: 0x000000006d063338
  rdi: 0x0000600002f33330  rsi: 0x0000000000000000  rbp: 0x00007ff7b83cf5f0  rsp: 0x00007ff7b83cf5d0
   r8: 0x0000000000000400   r9: 0x00000000000003ff  r10: 0x0000000000003370  r11: 0x0000600002f3ccbc
  r12: 0x000000000000008f  r13: 0x00000000000000b5  r14: 0x00007fa2f883ae00  r15: 0x00007fa2f883b6c0
  rip: 0x0000000107c69df5  rfl: 0x0000000000010206  cr2: 0x000020730e633350
  
Logical CPU:     0
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Thread 0 instruction stream:
  e8 56 9e 00 00 49 8b 07-48 83 78 10 00 74 06 48  .V...I..H.x..t.H
  8b 58 20 eb 24 48 89 c3-48 83 c3 08 eb 1b 66 2e  .X .$H..H.....f.
  0f 1f 84 00 00 00 00 00-0f 1f 00 48 89 df e8 92  ...........H....
  c5 32 00 48 89 c3 49 8b-07 8b 08 83 f9 02 72 0b  .2.H..I.......r.
  4c 89 ff e8 13 9e 00 00-49 8b 07 48 83 c0 08 48  L.......I..H...H
  39 c3 74 11 48 8b 7b 20-48 85 ff 74 ce 48 8b 07  9.t.H.{ H..t.H..
 [ff]50 20 eb c6 4c 89 ff-e8 1e 00 00 00 49 81 c6  .P ..L.......I..	<==
  c8 08 00 00 4c 89 f7 48-83 c4 08 5b 41 5e 41 5f  ....L..H...[A^A_
  5d e9 85 2d 10 00 0f 1f-44 00 00 55 48 89 e5 41  ]..-....D..UH..A
  57 41 56 53 50 48 8b 1f-4c 8b 35 9c 82 3e 00 4c  WAVSPH..L.5..>.L
  89 37 8b 03 83 f8 ff 74-5c 85 c0 74 06 f0 83 2b  .7.....t\..t...+
  01 75 52 4c 8b 7b 10 4d-85 ff 74 41 49 8b 7f 18  .uRL.{.M..tAI...

Binary Images:
       0x107b2e000 -        0x108051fff www.itdp.cn.Notepad-- (*) <f7715ad1-5f59-3840-bdd4-1ec3219da6a9> /Applications/Notepad--.app/Contents/MacOS/Notepad--
       0x109baf000 -        0x10a0e5fff org.qt-project.QtCore (5.12) <286c32b0-e13d-3600-ad17-2b6088ac2fb9> /Applications/Notepad--.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x108777000 -        0x108bb6fff org.qt-project.QtWidgets (5.12) <30358ca6-cd21-3a20-b7db-96603a913704> /Applications/Notepad--.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x1095c0000 -        0x109727fff libqcocoa.dylib (*) <ce87fda6-dd0a-3aa2-b318-d75e300c67df> /Applications/Notepad--.app/Contents/PlugIns/platforms/libqcocoa.dylib
    0x7ff80e862000 -     0x7ff80ecfafff com.apple.CoreFoundation (6.9) <dbc459f3-81bb-398a-8f74-3f7392392bb7> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff818191000 -     0x7ff818488ff2 com.apple.HIToolbox (2.1.1) <ff73b93b-3c5b-3f73-948f-0a35a80f7fad> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff8119c3000 -     0x7ff8129c7ff6 com.apple.AppKit (6.9) <817d572e-eb8c-3999-b7a0-68e1c4b47266> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff80e4cf000 -     0x7ff80e56354f dyld (*) <28fd2071-57f3-3873-87bf-e4f674a82de6> /usr/lib/dyld
    0x7ff80e7c6000 -     0x7ff80e7ffff7 libsystem_kernel.dylib (*) <0c2fd2c9-777c-3355-b70f-7b1b6e9d1b0b> /usr/lib/system/libsystem_kernel.dylib
    0x7ff80e800000 -     0x7ff80e80bff7 libsystem_pthread.dylib (*) <13b5e252-77d1-31e1-888d-1c5f4426ea87> /usr/lib/system/libsystem_pthread.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 16
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=795.5M resident=0K(0%) swapped_out_or_unallocated=795.5M(100%)
Writable regions: Total=716.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=716.9M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               640K        5 
Activity Tracing                   256K        1 
CG backing stores                 2528K        4 
CG image                          5496K       33 
ColorSync                          244K       28 
CoreAnimation                     27.1M       25 
CoreGraphics                        12K        2 
CoreImage                          256K        1 
CoreUI image data                 1788K       14 
Foundation                          40K        2 
Kernel Alloc Once                    8K        1 
MALLOC                           286.5M       88 
MALLOC guard page                   32K        6 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        6 
Stack                             10.5M        6 
VM_ALLOCATE                        148K       19 
__CTF                               756        1 
__DATA                            32.4M      596 
__DATA_CONST                      38.2M      368 
__DATA_DIRTY                      1751K      212 
__FONT_DATA                        2352        1 
__LINKEDIT                       185.8M       29 
__OBJC_RO                         65.1M        1 
__OBJC_RW                         1982K        2 
__TEXT                           609.7M      614 
dyld private memory                256K        1 
mapped file                      302.5M       57 
shared memory                      780K       19 
===========                     =======  ======= 
TOTAL                              2.0G     2143 
TOTAL, minus reserved VM space     1.6G     2143 

-----------
Full Report
-----------

{"app_name":"Notepad--","timestamp":"2023-02-08 23:40:05.00 +0800","app_version":"","slice_uuid":"f7715ad1-5f59-3840-bdd4-1ec3219da6a9","build_version":"","platform":1,"bundleID":"www.itdp.cn.Notepad--","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0.1 (22A400)","roots_installed":0,"name":"Notepad--","incident_id":"70E19811-D49F-47E5-A581-4C9EEBA427EB"}
{
  "uptime" : 5100,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro16,2",
  "coalitionID" : 1121,
  "osVersion" : {
    "train" : "macOS 13.0.1",
    "build" : "22A400",
    "releaseType" : "User"
  },
  "captureTime" : "2023-02-08 23:40:05.4645 +0800",
  "incident" : "70E19811-D49F-47E5-A581-4C9EEBA427EB",
  "pid" : 3246,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-02-08 23:01:47.2575 +0800",
  "procStartAbsTime" : 2834553828891,
  "procExitAbsTime" : 5132849742750,
  "procName" : "Notepad--",
  "procPath" : "\/Applications\/Notepad--.app\/Contents\/MacOS\/Notepad--",
  "bundleInfo" : {"CFBundleIdentifier":"www.itdp.cn.Notepad--"},
  "storeInfo" : {"deviceIdentifierForVendor":"A539BFC5-AC0D-5EB5-B888-3E61D5F122B9","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "www.itdp.cn.Notepad--",
  "crashReporterKey" : "769F9CF1-8B16-6607-C41A-1981E205D39F",
  "bridgeVersion" : {"build":"20P420","train":"7.0"},
  "sip" : "enabled",
  "vmRegionInfo" : "0x20730e633350 is not in any region.  Bytes after previous region: 35673608717137  Bytes before following region: 69874581556400\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      CoreAnimation               125559000-1259cb000    [ 4552K] rw-\/rwx SM=PRV  \n--->  GAP OF 0x5ffeda635000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "exception" : {"codes":"0x0000000000000001, 0x000020730e633350","rawCodes":[1,35678534710096],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x000020730e633350"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":3246},
  "vmregioninfo" : "0x20730e633350 is not in any region.  Bytes after previous region: 35673608717137  Bytes before following region: 69874581556400\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      CoreAnimation               125559000-1259cb000    [ 4552K] rw-\/rwx SM=PRV  \n--->  GAP OF 0x5ffeda635000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":16},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":44522,"instructionState":{"instructionStream":{"bytes":[232,86,158,0,0,73,139,7,72,131,120,16,0,116,6,72,139,88,32,235,36,72,137,195,72,131,195,8,235,27,102,46,15,31,132,0,0,0,0,0,15,31,0,72,137,223,232,146,197,50,0,72,137,195,73,139,7,139,8,131,249,2,114,11,76,137,255,232,19,158,0,0,73,139,7,72,131,192,8,72,57,195,116,17,72,139,123,32,72,133,255,116,206,72,139,7,255,80,32,235,198,76,137,255,232,30,0,0,0,73,129,198,200,8,0,0,76,137,247,72,131,196,8,91,65,94,65,95,93,233,133,45,16,0,15,31,68,0,0,85,72,137,229,65,87,65,86,83,80,72,139,31,76,139,53,156,130,62,0,76,137,55,139,3,131,248,255,116,92,133,192,116,6,240,131,43,1,117,82,76,139,123,16,77,133,255,116,65,73,139,127,24],"offset":96}},"threadState":{"r13":{"value":181},"rax":{"value":35678534710064},"rflags":{"value":66054},"cpu":{"value":0},"r14":{"value":140337930808832},"rsi":{"value":0},"r8":{"value":1024},"cr2":{"value":35678534710096},"rdx":{"value":1829122872},"r10":{"value":13168},"r9":{"value":1023},"r15":{"value":140337930811072},"rbx":{"value":105553152684128},"trap":{"value":14,"description":"(no mapping for user data read)"},"err":{"value":4},"r11":{"value":105553165798588},"rip":{"value":4425424373,"matchesCrashFrame":1},"rbp":{"value":140701924652528},"rsp":{"value":140701924652496},"r12":{"value":143},"rcx":{"value":1},"flavor":"x86_THREAD_STATE","rdi":{"value":105553165759280}},"queue":"com.apple.main-thread","frames":[{"imageOffset":1293813,"symbol":"CCNotePad::slot_clearHistoryOpenList()","symbolLocation":133,"imageIndex":0},{"imageOffset":2211084,"symbol":"QMetaObject::activate(QObject*, int, int, void**)","symbolLocation":3132,"imageIndex":1},{"imageOffset":28693,"symbol":"QAction::activate(QAction::ActionEvent)","symbolLocation":309,"imageIndex":2},{"imageOffset":2180033,"symbol":"QObject::event(QEvent*)","symbolLocation":753,"imageIndex":1},{"imageOffset":67165,"symbol":"QApplicationPrivate::notify_helper(QObject*, QEvent*)","symbolLocation":269,"imageIndex":2},{"imageOffset":72193,"symbol":"QApplication::notify(QObject*, QEvent*)","symbolLocation":497,"imageIndex":2},{"imageOffset":2009508,"symbol":"QCoreApplication::notifyInternal2(QObject*, QEvent*)","symbolLocation":212,"imageIndex":1},{"imageOffset":2014174,"symbol":"QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)","symbolLocation":878,"imageIndex":1},{"imageOffset":224025,"imageIndex":3},{"imageOffset":225928,"imageIndex":3},{"imageOffset":519112,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__","symbolLocation":17,"imageIndex":4},{"imageOffset":519031,"symbol":"__CFRunLoopDoSource0","symbolLocation":157,"imageIndex":4},{"imageOffset":518481,"symbol":"__CFRunLoopDoSources0","symbolLocation":212,"imageIndex":4},{"imageOffset":513483,"symbol":"__CFRunLoopRun","symbolLocation":929,"imageIndex":4},{"imageOffset":510896,"symbol":"CFRunLoopRunSpecific","symbolLocation":560,"imageIndex":4},{"imageOffset":195542,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":5},{"imageOffset":194566,"symbol":"ReceiveNextEventCommon","symbolLocation":199,"imageIndex":5},{"imageOffset":194339,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":70,"imageIndex":5},{"imageOffset":256823,"symbol":"_DPSNextEvent","symbolLocation":909,"imageIndex":6},{"imageOffset":252344,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1219,"imageIndex":6},{"imageOffset":196595,"symbol":"-[NSApplication run]","symbolLocation":586,"imageIndex":6},{"imageOffset":221187,"imageIndex":3},{"imageOffset":1990543,"symbol":"QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)","symbolLocation":431,"imageIndex":1},{"imageOffset":2011058,"symbol":"QCoreApplication::exec()","symbolLocation":130,"imageIndex":1},{"imageOffset":694556,"symbol":"main","symbolLocation":1004,"imageIndex":0},{"imageOffset":25360,"symbol":"start","symbolLocation":2432,"imageIndex":7}]},{"id":44558,"name":"com.apple.NSEventThread","frames":[{"imageOffset":5794,"symbol":"mach_msg2_trap","symbolLocation":10,"imageIndex":8},{"imageOffset":63101,"symbol":"mach_msg2_internal","symbolLocation":82,"imageIndex":8},{"imageOffset":34586,"symbol":"mach_msg_overwrite","symbolLocation":723,"imageIndex":8},{"imageOffset":6537,"symbol":"mach_msg","symbolLocation":19,"imageIndex":8},{"imageOffset":519438,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":145,"imageIndex":4},{"imageOffset":513914,"symbol":"__CFRunLoopRun","symbolLocation":1360,"imageIndex":4},{"imageOffset":510896,"symbol":"CFRunLoopRunSpecific","symbolLocation":560,"imageIndex":4},{"imageOffset":1697430,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":6},{"imageOffset":25177,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":9},{"imageOffset":7291,"symbol":"thread_start","symbolLocation":15,"imageIndex":9}]},{"id":44743,"name":"QThread","frames":[{"imageOffset":33722,"symbol":"poll","symbolLocation":10,"imageIndex":8},{"imageOffset":2363696,"symbol":"qt_safe_poll(pollfd*, unsigned int, timespec const*)","symbolLocation":608,"imageIndex":1},{"imageOffset":2369831,"symbol":"QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)","symbolLocation":903,"imageIndex":1},{"imageOffset":1990543,"symbol":"QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)","symbolLocation":431,"imageIndex":1},{"imageOffset":136044,"symbol":"QThread::exec()","symbolLocation":140,"imageIndex":1},{"imageOffset":140003,"imageIndex":1},{"imageOffset":25177,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":9},{"imageOffset":7291,"symbol":"thread_start","symbolLocation":15,"imageIndex":9}]},{"id":74965,"frames":[{"imageOffset":7256,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":75462,"frames":[{"imageOffset":7256,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":75464,"frames":[{"imageOffset":7256,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4424130560,
    "CFBundleIdentifier" : "www.itdp.cn.Notepad--",
    "size" : 5390336,
    "uuid" : "f7715ad1-5f59-3840-bdd4-1ec3219da6a9",
    "path" : "\/Applications\/Notepad--.app\/Contents\/MacOS\/Notepad--",
    "name" : "Notepad--"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4458213376,
    "CFBundleShortVersionString" : "5.12",
    "CFBundleIdentifier" : "org.qt-project.QtCore",
    "size" : 5468160,
    "uuid" : "286c32b0-e13d-3600-ad17-2b6088ac2fb9",
    "path" : "\/Applications\/Notepad--.app\/Contents\/Frameworks\/QtCore.framework\/Versions\/5\/QtCore",
    "name" : "QtCore",
    "CFBundleVersion" : "5.12.12"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4437012480,
    "CFBundleShortVersionString" : "5.12",
    "CFBundleIdentifier" : "org.qt-project.QtWidgets",
    "size" : 4456448,
    "uuid" : "30358ca6-cd21-3a20-b7db-96603a913704",
    "path" : "\/Applications\/Notepad--.app\/Contents\/Frameworks\/QtWidgets.framework\/Versions\/5\/QtWidgets",
    "name" : "QtWidgets",
    "CFBundleVersion" : "5.12.12"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4451991552,
    "size" : 1474560,
    "uuid" : "ce87fda6-dd0a-3aa2-b318-d75e300c67df",
    "path" : "\/Applications\/Notepad--.app\/Contents\/PlugIns\/platforms\/libqcocoa.dylib",
    "name" : "libqcocoa.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703372288000,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 4820992,
    "uuid" : "dbc459f3-81bb-398a-8f74-3f7392392bb7",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1953.1"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703532912640,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3112947,
    "uuid" : "ff73b93b-3c5b-3f73-948f-0a35a80f7fad",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703424065536,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 16797687,
    "uuid" : "817d572e-eb8c-3999-b7a0-68e1c4b47266",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2299"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703368540160,
    "size" : 607568,
    "uuid" : "28fd2071-57f3-3873-87bf-e4f674a82de6",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703371649024,
    "size" : 237560,
    "uuid" : "0c2fd2c9-777c-3355-b70f-7b1b6e9d1b0b",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703371886592,
    "size" : 49144,
    "uuid" : "13b5e252-77d1-31e1-888d-1c5f4426ea87",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 140703367933952,
  "size" : 21474836480,
  "uuid" : "840e528a-0c70-3c6a-b7b4-4f05f32ccc51"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=795.5M resident=0K(0%) swapped_out_or_unallocated=795.5M(100%)\nWritable regions: Total=716.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=716.9M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               640K        5 \nActivity Tracing                   256K        1 \nCG backing stores                 2528K        4 \nCG image                          5496K       33 \nColorSync                          244K       28 \nCoreAnimation                     27.1M       25 \nCoreGraphics                        12K        2 \nCoreImage                          256K        1 \nCoreUI image data                 1788K       14 \nFoundation                          40K        2 \nKernel Alloc Once                    8K        1 \nMALLOC                           286.5M       88 \nMALLOC guard page                   32K        6 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        6 \nStack                             10.5M        6 \nVM_ALLOCATE                        148K       19 \n__CTF                               756        1 \n__DATA                            32.4M      596 \n__DATA_CONST                      38.2M      368 \n__DATA_DIRTY                      1751K      212 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       185.8M       29 \n__OBJC_RO                         65.1M        1 \n__OBJC_RW                         1982K        2 \n__TEXT                           609.7M      614 \ndyld private memory                256K        1 \nmapped file                      302.5M       57 \nshared memory                      780K       19 \n===========                     =======  ======= \nTOTAL                              2.0G     2143 \nTOTAL, minus reserved VM space     1.6G     2143 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000247
    },
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {

      },
      "deploymentId" : 240000213
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro16,2, BootROM 1916.40.8.0.0 (iBridge: 20.16.420.0.0,0), 4 processors, Quad-Core Intel Core i5, 2 GHz, 16 GB, SMC 
Graphics: Intel Iris Plus Graphics, Intel Iris Plus Graphics, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR4X, 3733 MHz, SK Hynix, H9HCNNNCPMALHR-NEE
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR4X, 3733 MHz, SK Hynix, H9HCNNNCPMALHR-NEE
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Sep 14 2022 18:03:20 version 9.30.489.3.32.5.84 FWID 01-8b6fe36e
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: T2Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 86.0
Thunderbolt Bus: MacBook Pro, Apple Inc., 86.0

**Comment by cxasm** [comment]
感谢反馈。

**Comment by cxasm** [comment]
重新发布了 1.22.2的 mac版本，解决了这里的崩溃问题，还请更新重试。感谢反馈。
